# Experimenting with hybrid search in out Qdrant DB

In [38]:
from dotenv import load_dotenv
load_dotenv("../../.env")

import openai
import pandas as pd

from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance, SparseVectorParams, Modifier, PayloadSchemaType, PointStruct, Document, Prefetch, RrfQuery, Rrf

### New Collection for hybrid search

In [2]:
qdrant_client = QdrantClient(url="localhost:6333")

In [4]:
from numpy import size
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-hybrid-search",
    vectors_config={
        "text-embedding-3-small": VectorParams(size=1536, distance=Distance.COSINE),
    },
    sparse_vectors_config={
        "bm25": SparseVectorParams(modifier=Modifier.IDF),
    }
)

True

In [5]:
qdrant_client.create_payload_index(
    collection_name="Amazon-items-collection-hybrid-search",
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

### Embedding Functions

In [7]:
def get_embeddings_batch(text_list, model="text-embedding-3-small", batch_size=100):
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]

    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend(
            [embedding.embedding for embedding in response.data]
        )

        print(f"Batch #{counter}: {counter * batch_size} / {len(text_list)}")
        counter += 1

    return all_embeddings

### Read the sampled dataset with Amazon inventory data

In [8]:
df_items = pd.read_json("../../data/meta_Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [9]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,AMAZON FASHION,"Bosttor Bluetooth Beanie Hat with Light, Headl...",4.5,2342,"[100% Acrylic, Elastic closure, Hand Wash Only...",[],26.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Beanie Hat with Bluetooth Headphon...,Bosttor,"[Electronics, Headphones, Earbuds & Accessorie...","{'Department': 'unisex-adult', 'Date First Ava...",B0BH41HYFZ,NaN,NaN,NaN
1,All Electronics,"Aceele USB and USB C to Ethernet Adapter, 3.3f...",4.2,148,[【USB or USB C to Ethernet Adapter】The Etherne...,[],14.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aceele,"[Electronics, Computers & Accessories, Network...",{'Product Dimensions': '3.54 x 0.98 x 0.71 inc...,B0BKPB2YQ9,NaN,NaN,NaN
2,All Electronics,HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Sp...,4.2,3331,[📍3-Port HDMI Switch: This aluminum HDMI switc...,[],18.98,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Darren reviews VWRHAR 3-1 splitter...,VWRHar,"[Electronics, Home Audio, Home Audio Accessori...",{'Package Dimensions': '6.1 x 4.21 x 0.94 inch...,B09MM5QT3R,NaN,NaN,NaN
3,All Electronics,"Smart Watch,Ip67 Waterproof Bluetooth Smartwat...",3.4,125,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Burxoe,[],{'Package Dimensions': '3.15 x 3.07 x 2.52 inc...,B09Q5TNDHY,NaN,NaN,NaN
4,Cell Phones & Accessories,"(3 Pack) Cute Airpod Case for Airpods 2&1,3D D...",4.7,335,[【Compatible Airpods 1/2 】This case designed f...,[1],11.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'airpod cases', 'url': 'https://www...",UGUHY,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '7.44 x 4.61 x 1.57 inc...,B0BZJKX7MS,NaN,NaN,NaN

### Preprocess title and features

In [10]:
def preprocess_description(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [11]:
def extract_first_large_image(row):
    return row["images"][0].get("large", "")

In [12]:
df_items["preprocessed_description"] = df_items.apply(preprocess_description, axis=1)
df_items["image"] = df_items.apply(extract_first_large_image, axis=1)

In [13]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,preprocessed_description,image
0,AMAZON FASHION,"Bosttor Bluetooth Beanie Hat with Light, Headl...",4.5,2342,"[100% Acrylic, Elastic closure, Hand Wash Only...",[],26.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Beanie Hat with Bluetooth Headphon...,Bosttor,"[Electronics, Headphones, Earbuds & Accessorie...","{'Department': 'unisex-adult', 'Date First Ava...",B0BH41HYFZ,NaN,NaN,NaN,"Bosttor Bluetooth Beanie Hat with Light, Headl...",https://m.media-amazon.com/images/I/51b7qcj8dZ...
1,All Electronics,"Aceele USB and USB C to Ethernet Adapter, 3.3f...",4.2,148,[【USB or USB C to Ethernet Adapter】The Etherne...,[],14.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aceele,"[Electronics, Computers & Accessories, Network...",{'Product Dimensions': '3.54 x 0.98 x 0.71 inc...,B0BKPB2YQ9,NaN,NaN,NaN,"Aceele USB and USB C to Ethernet Adapter, 3.3f...",https://m.media-amazon.com/images/I/41WsGRr-3T...
2,All Electronics,HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Sp...,4.2,3331,[📍3-Port HDMI Switch: This aluminum HDMI switc...,[],18.98,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Darren reviews VWRHAR 3-1 splitter...,VWRHar,"[Electronics, Home Audio, Home Audio Accessori...",{'Package Dimensions': '6.1 x 4.21 x 0.94 inch...,B09MM5QT3R,NaN,NaN,NaN,HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Sp...,https://m.media-amazon.com/images/I/41fsjaknf1...
3,All Electronics,"Smart Watch,Ip67 Waterproof Bluetooth Smartwat...",3.4,125,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Burxoe,[],{'Package Dimensions': '3.15 x 3.07 x 2.52 inc...,B09Q5TNDHY,NaN,NaN,NaN,"Smart Watch,Ip67 Waterproof Bluetooth Smartwat...",https://m.media-amazon.com/images/I/51YFypeuZh...
4,Cell Phones & Accessories,"(3 Pack) Cute Airpod Case for Airpods 2&1,3D D...",4.7,335,[【Compatible Airpods 1/2 】This case designed f...,[1],11.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'airpod cases', 'url': 'https://www...",UGUHY,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '7.44 x 4.61 x 1.57 inc...,B0BZJKX7MS,NaN,NaN,NaN,"(3 Pack) Cute Airpod Case for Airpods 2&1,3D D...",https://m.media-amazon.com/images/I/41V7Wi2ckb...

In [14]:
list(df_items["preprocessed_description"].items())[0]

(0,
 'Bosttor Bluetooth Beanie Hat with Light, Headlamp Cap with Headphones and Built-in Speaker Mic, Gifts for Men Women Teen 100% Acrylic Elastic closure Hand Wash Only 【Upgraded Bluetooth Beanie】Bosttor upgraded Bluetooth wireless technology offer much stable and strong connection, support music and calling, easy and fast to pair with your devices. Maximum transmission distance up to 33 feet. Built-in Stereo Speakers & Mic, enhance your music listening experience. 【Long Working Time Music Hat】Built with easy-access USB charging port, simply charge it via the included USD cable. It takes 1-2 hours to get full charged. The battery offers continuous working hours up to 10 hours. Perfect for camping, hiking, skiing, hunting, jogging, cycling, dog walking, auto repair, etc. 【LED Headlight Light Up Your Way】Hands-free LED light is rechargeable and removable. You can remove it to charge by laptop, power bank, socket, car charger, etc. The 4 LED lights can light up to 30 feet away. It points directional light toward what your eyes are looking at. It has 3 brightness settings. 【One Size Fits Most】Bosttor unisex beanie hat is made from the ultra-soft acrylic blend material that provides excellent insulation against cold winter air. Elastic and comfortable LED hat fits men women and teens. It is hand washable, please remove the LED and the headset before washing. 【Ideal Birthday & Christmas Gifts】Our beanie hat with Bluetooth and LED headlight is the ideal gift for runners and outdoor adventurers in winter. It is also your best gift choice for men women and teenagers. This is the perfect gift for anyone in the family and your friends. Your Ideal choice for Thanksgiving Day, Christmas, Birthday and Anniversary.')

In [15]:
list(df_items["image"].items())[0]

(0, 'https://m.media-amazon.com/images/I/51b7qcj8dZL._AC_.jpg')

### Sample 50 items from the dataset

In [16]:
df_sample = df_items.sample(n=50, random_state=42)

In [17]:
df_data_to_embed = df_sample[["preprocessed_description", "image", "rating_number", "price", "average_rating", "parent_asin"]]

In [18]:
df_data_to_embed.head()

,preprocessed_description,image,rating_number,price,average_rating,parent_asin
521,Marame 120mm 5v USB Powered Fan with Speed Con...,https://m.media-amazon.com/images/I/41Zpg4vSEj...,104,14.99,4.7,B0BRJS644Z
737,"Kids Wireless Headphones, Adjustable Headband,...",https://m.media-amazon.com/images/I/41+jaEbUbY...,173,NaN,4.2,B09KQP2H7N
740,"Veetone Aux Cord for iPhone, 3.3ft [Apple MFi ...",https://m.media-amazon.com/images/I/31ag2Blvjm...,2218,5.99,4.0,B0CC4HBS85
660,AICHESON Laptop Cooler Pad with 6 Cooling Fans...,https://m.media-amazon.com/images/I/51BKtk3-RD...,145,NaN,4.2,B099N9F3FP
411,"Raymate Bluetooth Speakers, HiFi Stereo Sound ...",https://m.media-amazon.com/images/I/31SnPdXS77...,270,38.69,4.7,B0C996WY16

In [19]:
data_to_embed = df_data_to_embed.to_dict(orient="records")

In [20]:
data_to_embed

[{'preprocessed_description': 'Marame 120mm 5v USB Powered Fan with Speed Controller Cooling for Router Modem Receiver DVR Xbox TV Box (120mm x 120mm x 55mm) 【Solve Your Cooling Problem】\xa0This fan will do the job keeping your devices from overheating and keep your electronics running cool. You can also use them in confined spaces for cooling various electronics. blowing cool air through it to aid in longevity. 【Speed\xa0Control\xa0Switch】 The speed controller located on the cord allows you to adjust the fan’s speed from off to low, medium, and high. This enables you to set the fan to optimal noise and airflow levels for various environments. 【High Compatibility USB-Powered】 Powered by a 3.3ft USB cable. Compatible with desktop, laptop, power bank, AC adapters, car chargers, and other power supplies that support USB connection. USB fan is energy-saving and environmentally friendly. 【Rubber Feet & Dust Filter】\xa0Rubber Feet on the fan raise it up enough off of the surface it is sitting on to allow enough replacement air to be drawn in, under the suction side of the fan. rubber feet with non-slip pads to keep this fan from sliding and absorbs any vibration noise.\xa0Dust Filter on the fan both sides. does not blow dirt or dust onto your devices. 【Widely Applications】It is works great to cool an airflow-restricted entertainment center. such as cooling for Router TV Box\xa0\xa0Modem X-box Audio Receiver Cabinet Stereo Amplifier.',
  'image': 'https://m.media-amazon.com/images/I/41Zpg4vSEjL.jpg',
  'rating_number': 104,
  'price': 14.99,
  'average_rating': 4.7,
  'parent_asin': 'B0BRJS644Z'},
 {'preprocessed_description': "Kids Wireless Headphones, Adjustable Headband, Stereo Sound, 3.5mm Jack, Kids Bluetooth Headphones, Volume Control, Foldable, Build-in Microphone, Over-Ear Headphones for Kids for School Home, Yellow 【WIRELESS & WIRED KIDS HEADPHONES】 Stunning kid headphones, built with the latest high quality 5.0 Bluetooth chip, which allows kids wireless headphones to connect fast and stable, also with 3.5mm jack to connect any device. You can use them as wireless headphones and wired headphones, compatible with smartphones, laptops, tablets, computers, TVs and many other Bluetooth-enabled devices, making it possible to provide you with great music anywhere in the occasion. 【Cute cat headphones】It is designed with cute cartoon pattern, you can use it in any venue. Our over-ear headphones provide you with easy to control high quality sound, comfortable and soft ear cushions can protect your child's ears well, it is a beautiful birthday or Christmas gift for girls, children, teenagers, adult women. 【Excellent sound quality and adjustable headband】 This baby headphones is designed for children, no need to worry about the damage caused by rough handling. Stretchable, foldable design is convenient for travel and storage. Clear stereo sound quality provides you with the best listening enjoyment, full sound, supports connection to Bluetooth, 3.5mm headphone jack, SD card, connect and enjoy all the favorite content for boys and girls. 【Long battery life and built-in microphone】Our toddler headphones have a battery capacity of up to 400mAh and last up to 7 hours, so even when the battery runs out, you can still use it through the audio hole. Built-in microphone for taking calls, video chats, or online lessons. Perfect for: kids headphones for school, outdoor headphones for boys and girls Yellow cartoon headphones 【100% satisfaction after-sales service】 Our brand always puts customers first, if you have any problems with your headphones, please feel free to contact us through seller support, we will provide you with attentive customer service within 24 hours.",
  'image': 'https://m.media-amazon.com/images/I/41+jaEbUbYL._AC_.jpg',
  'rating_number': 173,
  'price': nan,
  'average_rating': 4.2,
  'parent_asin': 'B09KQP2H7N'},
 {'preprocessed_description': 'Veetone Aux Cord for iPhone, 3.3ft [Apple MFi Certified] Lightning to 3.5mm AUX Audio Cable Compatible with iPhone 14 13 12 11 XS XR X 8 7 6 for Home Car Stereo/Headphone/Speaker, Support All iOS 【2023 Newest Version】 Newest Apple MFi chips make this aux cord for car can support all iOS version and compatible with iPhone 14/14 Pro/14 Pro Max/14 Plus/13/13 Pro/13 Pro Max/13 Mini/12/12 Pro/12 Pro Max/12 Mini/11/11 Pro/Xs/XS Max/X/8/8 Plus/7/7 Plus and more. Easily play audio from your iPhone on car stereo, headphone, Hi-Fi, speaker with 3.5mm aux ports or other 3.5mm-compatible audio output devices. 【Plug and Play】 No need any driver or adapter, enjoy high quality music instantly. Ultra-thin extensions of the connector enable fit with most of phone case, No need to remove cases for more convenient use. The aux to lightning cable allows you to enjoy high-quality music anytime and anywhere. 【Enjoy Hi-Fi Music】 This aux cord for iPhone car adapter was built-in newest powerful DAC chip and premium copper wires to ensures stable and lossless sound transmission of audio signal, provide flawlessly music transmission and clear Hi-Fi sound quality. You can enjoy high quality music via connecting your iPhone to your car or home stereo, headphones, Hi-Fi, computer stereo etc. 【Ultra Durability】 The lightning to 3.5 mm audio cable is made of high-quality polished metal connector, gold-plated 3.5mm conductor and durable stretch plastic wire material, fast and sturdy connection, protect it from breaking, 100% durable to use.The auxiliary line is 1 meters long, which can be a better use when you are listening to music in the car. 【Powerful Functions】 The iPhone aux cord for car enables you to play audio on your car stereo, headphone, Hi-Fi, computer stereo, bluetooth speaker with 3.5mm aux ports or other 3.5mm compatible output devices. Great for home & travel. This aux cord for iPhone 13 14 is a good choice as a gift for your family or friends.',
  'image': 'https://m.media-amazon.com/images/I/31ag2BlvjmL.jpg',
  'rating_number': 2218,
  'price': 5.99,
  'average_rating': 4.0,
  'parent_asin': 'B0CC4HBS85'},
 {'preprocessed_description': 'AICHESON Laptop Cooler Pad with 6 Cooling Fans for 11" - 15.6" Laptops, RED Lights Super Laptop Cooling Fans - AICHESON cooling pads laptop is specially designed with 6 (70mm) cooling fans, each fan speed is 1500-2200RPM from level 1 to level 6, providing you adjustable airflows to lengthen the life of your laptop Ergonomic Heights Stands - Once the hook is dropped, it is locked in position, and it is very convenient to adjust the angles and heights, angles can change from 10 to 27 degrees, raising your laptop up 2.83" to 5.19", providing you a better and a more comfortable posture when using the laptop Low Noise and Easy Operation - Even structured with 6 cooling fans, the noise level is 25dBA - 28 dBA, which is just like someone whispers around your ear. And the LCD display control panel allows you to adjust fan speed easily. There is no need to wrap your hands behind the cooler to operate, which is very troublesome 3 Modes and Extra USB Ports - Long pressing the ON/OFF button to adjust modes from 1, 2, 3, it\'s free to choose according to the situation. Extra USB ports allow you to connect a mouse, a keyboard. 2 small hidden anti-slip pads are helpful to protect your laptop, please remember to open them Widely Compatibility - The laptop fan cooling pad is compatible with all laptops from 13" to 15.6", and weighs 1.6LB, measures 14.56" x 10.43" x 1.26", portable for you to carry with your laptop.',
  'image': 'https://m.media-amazon.com/images/I/51BKtk3-RDL._AC_.jpg',
  'rating_number': 145,
  'price': nan,
  'average_rating': 4.2,
  'parent_asin': 'B099N9F3FP'},
 {'preprocessed_description': 'Raymate Bluetooth Speakers, HiFi Stereo Sound with DSP, 30W IPX7 Waterproof Speaker Wireless Bluetooth-V5.0, 1000mins Playtime, Portable Speaker for Home, Outdoor, Party 🎶HiFi Sound: With proven audio processing DSP chip technology, 30W dual speaker drivers and a more powerful amplifier module, the portable speakers delivers even, Balanced Sound Without Distortion. 🧱Integrated structure: With IPX7 Waterproof Speakers protection against rain, dust, snow and splashes, you can enjoy music in the pool, beach, park, bathroom and beyond.Comes with a dirt and corrosion resistant portable silicone protective sleeve. ✨Simple And Stylish: This is a speaker with a golden ratio rectangular body, combined with the purest colors, perfect for a variety of venues. 🔋Extended Battery Life: 3600mAh high-capacity battery provides you with more than 1000mins of play time.This speaker uses a more stable charging port - type C port, which greatly saves your waiting time. Note: We provide a 180 day warranty service and a 24-hour customer service response service.',
  'image': 'https://m.media-amazon.com/images/I/31SnPdXS77L._AC_.jpg',
  'rating_number': 270,
  'price': 38.69,
  'average_rating': 4.7,
  'parent_asin': 'B0C996WY16'},
 {'preprocessed_description': "iPhone Charger Cord [Apple MFi Certified] Lightning Cable 1m/3.3FT Fast Charging High Speed Data Sync USB Cable Compatible with iPhone 14/13/12/11 Pro Max/XS MAX/XR/XS/X/8/7/Plus/6S iPad [Fast Charging & Sync] - iPhone Charger Cord Max 2.4 output current, high quality copper wire, improve charging and data transfer speed of iPhone charging cable. iPhone Lightning Cable ensures faster charging time and keeps your device safer. [Perfect comptibility] - iPhone lightning cables compatible with iPhone 14/14 Plus/14 Pro/14 Pro Max/iPhone 13/13 mini/13 Pro/13 Pro Max/12/12 mini/12 Pro/12 Pro Max/11/11 Pro/11 Pro Max/SE 2/XS/XS Max/XR/X/8Plus/8/7Plus/7/6s Plus/6s/6 Plus/6/5s/5c,iPad,AirPods [MFi Certified] - The lightning cable has an original lightning chip inside. Make sure it's compatible with your iPhone and charges your device safely. Enjoy fast data transfer, sync and charging. [Superior Durability] - iPhone lightning cable are made of top quality materials and coated with premium TPE. Passed 10,000 flex tests and won't get tangled for extra protection and durability. [What you get?] - 1x 3ft Mfi Certified iPhone Charging Cable. If you have any quality problems with our products, please feel free to contact us. We provide 24/7 customer support",
  'image': 'https://m.media-amazon.com/images/I/31CSP4L973L.jpg',
  'rating_number': 119,
  'price': 4.99,
  'average_rating': 4.4,
  'parent_asin': 'B0BN1CMWCP'},
 {'preprocessed_description': 'Skovlys Avocado Stickers for Water Bottles,Vinyl Waterproof Stickers for Water Bottle,50 Pcs Waterproof Vinyl Stickers for Water Bottle, Laptop, Phone Case, Guitaromputer,Phone,Guitar 🥑Avocado Stickers Pack,50pcs each pack, 50pcs no-duplicate stickers,2.5-3.5 inch each pcs 🥑3-layer structure, the surface layer is made of waterproof and scratch-resistant material, the printing layer is made of UV 7-color printing with bright colors, and the primer is made of PVC non-marking removable glue 🥑Our assortment of graffiti decals is your best choice when choosing a gift for your friends, kids. These creative patches will be the perfect present to make a cool room or for DIY decoration 🥑Stick them and use them for your Laptops, Skateboards, Luggage, Cars, Bikes, Bicycles, Bedroom, Travel Case, Bicycle, Motorcycle, Snowboard, PS4, XBOX ONE, etc.Guitar 🥑We are 100% guaranteed that you are completely satisfied with your product or receive your refund. We Partnered with Amazon FBA to give you the highest quality Amazon Prime shipping and hassle free returns.',
  'image': 'https://m.media-amazon.com/images/I/618pgbbaFnL._AC_.jpg',
  'rating_number': 128,
  'price': 5.99,
  'average_rating': 4.8,
  'parent_asin': 'B0B5CYWHWV'},
 {'preprocessed_description': '12 13 13.3 14 15.4 15.6 Inches Laptop Skin Sticker Decal Universal Netbook Skin Sticker | Need to Cut,Easy to Apply, Remove and Change Styles (Morning Glory) 100% Brand New and High Quality. Our laptop skins 15.6 inch，laptop skins 15.6 inch Fits up to 12.1"-15.6" laptops.High Resolution Printing. Flexible Film Helps Protect the Laptop Surface From Scratches & Smudges. We\'ve Made The Best Laptop Skin Sticker Decal Available and in a Variety of Wonderful Colors,PVC_Removable Layer & Paper layer; Three films aret of Our Way to Make Sure You are 100% Satisfied. Easy to Remove and Reuse .Will Last For Years and Won\'t Fade, Three Films are Included,one For the Back Side of The LCD Screen and Two For the Sides of the Touch Pad. About 38.0cm(15.0 inch) x 27.0cm( 10.6 inch);Compatible with :Most 12" ~ 15.6" wide Screen Notebook. The Sticker is Only One Size,You Maybe Need to Cut by Yourself to Fit Your Laptop. This is a No-Risk Purchase.If you have any questions for it ,No Hassle Refund Guaranteed.It can be a Sweet Gift Idea for Your Loved ones. We Will Go Out of Our Way to Make Sure You are 100% Satisfied.',
  'image': 'https://m.media-amazon.com/images/I/51VLMlQuP4L._AC_.jpg',
  'rating_number': 102,
  'price': 9.99,
  'average_rating': 4.1,
  'parent_asin': 'B09WCT9S1R'},
 {'preprocessed_description': 'Geiomoo Silicone Case Compatible with Anker Soundcore Sport X10, Protective Cover with Carabiner (Black) Perfectly matches with Anker Soundcore Sport X10 Made of high quality soft silicone, scratch proof, shock proof and durable Carabiner is included to improve the practicality 360° all-round protection Easy to install',
  'image': 'https://m.media-amazon.com/images/I/31jUk+YZzeL._AC_.jpg',
  'rating_number': 112,
  'price': 10.5,
  'average_rating': 4.2,
  'parent_asin': 'B0B76GG8L1'},
 {'preprocessed_description': 'TP-Link TL-SM331T | 1000Base-T RJ45 SFP Module | 1.25G Copper SFP Transceiver | SFP to Ethernet | Plug and Play | Hot Pluggable | Up to 100m distance | | Durable Metal Casing | Versatile Compatibility 【SFP to RJ45 1000Base-T Copper SFP】Transmit data seamlessly up to 100 meters between your SFP interface and the copper gigabit port. 【Wide Compatibility】Compatible with most fiber switches, media converters, routers or other fiber optic equipments with SFP ports, TL-SM331T provides additional copper cable connections for peace of mind. 【Easy for deployment】Plug and Play with no software installation or configuration/technician needed. 【Durable Metal Casing】Ensures strength and reliability for a long time, maintaining a stable connection in a wide range of environments. 【Hot Pluggable】Plug in or remove your SFP module without needing to shutdown your network. Hot swap-ability ensures your network always stays up.',
  'image': 'https://m.media-amazon.com/images/I/31XzyYFo3xL._AC_.jpg',
  'rating_number': 104,
  'price': 23.99,
  'average_rating': 4.5,
  'parent_asin': 'B09RMJWBSM'},
 {'preprocessed_description': 'Fire HD 8 & HD 8 Plus Tablet Case for Kids (Only 12th Gen, 2022 Release) - DJ&RPPQ Lightweight Shockproof Cover with Handle Stand for Kindle Fire HD 8 Kids Tablet & Kids Pro Tablet - Blue Designed for Amazon All-New Kindle Fire HD 8 & Fire HD 8 Plus Tablet, Fire HD 8 Kids tablet & Fire HD 8 Kids Pro tablet (12th Generation 2022 Release), NOT fit for other models. Cutouts for clear access to all Amazon Kindle Fire HD 8 Plus / Fire HD 8 Tablet(12TH Generation, 2022Release) / Fire HD 8 Kids Pro 2022Tablet buttons, ports, speakers and rear-camera. Raised screen bezel edges for extra protection when fall. Kindle fire 8 case made with dense heavy duty EVA foam, Material can withstand considerable wear and tear and provide extreme shock protection.Super light weight and durable hazard free safe material perfect for kids and grownups alike. Built-in Kickstand- Designed with a foldable kick-stand on the back of the case, allows you to set up multiple angles and gives you the hands-free convenience when watching videos and movies. All-New Kindle Fire HD 8/8 plus Tablet case x 1.(The tablet is not included, and NO screen protector included); About customer service: Any questions please feel free to contact us and we will reply as soon as possible within 24 hours.',
  'image': 'https://m.media-amazon.com/images/I/512AWwRyqzL._AC_.jpg',
  'rating_number': 739,
  'price': 12.99,
  'average_rating': 4.4,
  'parent_asin': 'B0BG6TMXDD'},
 {'preprocessed_description': 'Wekily Bluetooth 5.3 Headphones, Wireless Earbuds with 40H Playtimes Charge Case, Deep Bass, IPX7 Waterproof Running Earphones with 4-Mic Clear Call, LED Display, in Ear Headphones for Work/Gym Excellent Sound Quality: Wireless earbuds adopte graphene drivers and a polymer composite diaphragm carrying an AAC/SBC audio decoder, resulting in up to 43% bass enhancement. Audio technology is losslessly transmitted for a clearer stereo sound from the headphones. 40Hrs Cycle Playtimes: The 400mAh charging case has a playtime of 35 hours and the wireless headphones have a single playtime of 5hours of music. Quick charge in 10 minutes, 1 hour of use. In case of emergency. Bluetooth 5.3 Technology: The wireless headphones adopt bluetooth 5.3 chip, low battery consumption, fast transmission speed, and stable connection range up to 18m. Clear Call: Bluetooth earbuds adopt 4-microphone ENC reduction technology, combined with 13mm speakers, Making call is still very clear in public or gym environments. IPX7 Waterproof: Wireless sports earphones use nano-coating technology, waterproof and sweat-proof have passed the IPX7 standard, which is very suitable for your daily use.',
  'image': 'https://m.media-amazon.com/images/I/41qSQNF53EL._AC_.jpg',
  'rating_number': 2752,
  'price': 25.99,
  'average_rating': 4.4,
  'parent_asin': 'B0BRV544MV'},
 {'preprocessed_description': "seenda Wired Mouse - USB Computer Mouse Wired with RGB Backlit Optical LED Mouse with Attached USB Cord for Laptops Notebooks Chromebook - Rose Gold Play in A Colorful Way -- A optical wired computer mouse featuring with rainbow colored changing light around the base of the mouse, you can choose how they are displayed as well as the ability to turn the colors off when you're not using it Plug & Play Wired Mouse -- Plug it to your computers and and it's been working ever since, with no issues or need to change settings. The smooth tracking, quiet, soft-touch buttons and wheels would be added features Sleek & Comfortable Shape -- This computer mouse does all that it needs in a comfortable shape and size, fits well for both small hands and big hands. It has a long enough cord to reach your computer easily Responsive & Accurate Click -- The optical response to the computer its very good, moving cursors, scrolling pages makes seamless efforts in using this mouse Universal Compatibility -- Works with Notebook, Computer, PC, Laptop,Chromebook with USB port, running on Windows XP/Vista/7/8/10 Mac OS X 10.4 etc.【Notice:This product is not compatible with macbook pro or other laptops which only have type c ports】",
  'image': 'https://m.media-amazon.com/images/I/41czXlj4jSS._AC_.jpg',
  'rating_number': 163,
  'price': 9.99,
  'average_rating': 4.5,
  'parent_asin': 'B0BYD7PGV1'},

In [21]:
len(data_to_embed)

50

In [23]:
text_for_embedding = [item["preprocessed_description"] for item in data_to_embed]

In [24]:
text_for_embedding

['Marame 120mm 5v USB Powered Fan with Speed Controller Cooling for Router Modem Receiver DVR Xbox TV Box (120mm x 120mm x 55mm) 【Solve Your Cooling Problem】\xa0This fan will do the job keeping your devices from overheating and keep your electronics running cool. You can also use them in confined spaces for cooling various electronics. blowing cool air through it to aid in longevity. 【Speed\xa0Control\xa0Switch】 The speed controller located on the cord allows you to adjust the fan’s speed from off to low, medium, and high. This enables you to set the fan to optimal noise and airflow levels for various environments. 【High Compatibility USB-Powered】 Powered by a 3.3ft USB cable. Compatible with desktop, laptop, power bank, AC adapters, car chargers, and other power supplies that support USB connection. USB fan is energy-saving and environmentally friendly. 【Rubber Feet & Dust Filter】\xa0Rubber Feet on the fan raise it up enough off of the surface it is sitting on to allow enough replacement air to be drawn in, under the suction side of the fan. rubber feet with non-slip pads to keep this fan from sliding and absorbs any vibration noise.\xa0Dust Filter on the fan both sides. does not blow dirt or dust onto your devices. 【Widely Applications】It is works great to cool an airflow-restricted entertainment center. such as cooling for Router TV Box\xa0\xa0Modem X-box Audio Receiver Cabinet Stereo Amplifier.',
 "Kids Wireless Headphones, Adjustable Headband, Stereo Sound, 3.5mm Jack, Kids Bluetooth Headphones, Volume Control, Foldable, Build-in Microphone, Over-Ear Headphones for Kids for School Home, Yellow 【WIRELESS & WIRED KIDS HEADPHONES】 Stunning kid headphones, built with the latest high quality 5.0 Bluetooth chip, which allows kids wireless headphones to connect fast and stable, also with 3.5mm jack to connect any device. You can use them as wireless headphones and wired headphones, compatible with smartphones, laptops, tablets, computers, TVs and many other Bluetooth-enabled devices, making it possible to provide you with great music anywhere in the occasion. 【Cute cat headphones】It is designed with cute cartoon pattern, you can use it in any venue. Our over-ear headphones provide you with easy to control high quality sound, comfortable and soft ear cushions can protect your child's ears well, it is a beautiful birthday or Christmas gift for girls, children, teenagers, adult women. 【Excellent sound quality and adjustable headband】 This baby headphones is designed for children, no need to worry about the damage caused by rough handling. Stretchable, foldable design is convenient for travel and storage. Clear stereo sound quality provides you with the best listening enjoyment, full sound, supports connection to Bluetooth, 3.5mm headphone jack, SD card, connect and enjoy all the favorite content for boys and girls. 【Long battery life and built-in microphone】Our toddler headphones have a battery capacity of up to 400mAh and last up to 7 hours, so even when the battery runs out, you can still use it through the audio hole. Built-in microphone for taking calls, video chats, or online lessons. Perfect for: kids headphones for school, outdoor headphones for boys and girls Yellow cartoon headphones 【100% satisfaction after-sales service】 Our brand always puts customers first, if you have any problems with your headphones, please feel free to contact us through seller support, we will provide you with attentive customer service within 24 hours.",
 'Veetone Aux Cord for iPhone, 3.3ft [Apple MFi Certified] Lightning to 3.5mm AUX Audio Cable Compatible with iPhone 14 13 12 11 XS XR X 8 7 6 for Home Car Stereo/Headphone/Speaker, Support All iOS 【2023 Newest Version】 Newest Apple MFi chips make this aux cord for car can support all iOS version and compatible with iPhone 14/14 Pro/14 Pro Max/14 Plus/13/13 Pro/13 Pro Max/13 Mini/12/12 Pro/12 Pro Max/12 Mini/11/11 Pro/Xs/XS Max/X/8/8 Plus/7/7 Plus and more. Easily play audio from your iPhone on car stereo, headphone, Hi-Fi, speaker with 3.5mm aux ports or other 3.5mm-compatible audio output devices. 【Plug and Play】 No need any driver or adapter, enjoy high quality music instantly. Ultra-thin extensions of the connector enable fit with most of phone case, No need to remove cases for more convenient use. The aux to lightning cable allows you to enjoy high-quality music anytime and anywhere. 【Enjoy Hi-Fi Music】 This aux cord for iPhone car adapter was built-in newest powerful DAC chip and premium copper wires to ensures stable and lossless sound transmission of audio signal, provide flawlessly music transmission and clear Hi-Fi sound quality. You can enjoy high quality music via connecting your iPhone to your car or home stereo, headphones, Hi-Fi, computer stereo etc. 【Ultra Durability】 The lightning to 3.5 mm audio cable is made of high-quality polished metal connector, gold-plated 3.5mm conductor and durable stretch plastic wire material, fast and sturdy connection, protect it from breaking, 100% durable to use.The auxiliary line is 1 meters long, which can be a better use when you are listening to music in the car. 【Powerful Functions】 The iPhone aux cord for car enables you to play audio on your car stereo, headphone, Hi-Fi, computer stereo, bluetooth speaker with 3.5mm aux ports or other 3.5mm compatible output devices. Great for home & travel. This aux cord for iPhone 13 14 is a good choice as a gift for your family or friends.',
 'AICHESON Laptop Cooler Pad with 6 Cooling Fans for 11" - 15.6" Laptops, RED Lights Super Laptop Cooling Fans - AICHESON cooling pads laptop is specially designed with 6 (70mm) cooling fans, each fan speed is 1500-2200RPM from level 1 to level 6, providing you adjustable airflows to lengthen the life of your laptop Ergonomic Heights Stands - Once the hook is dropped, it is locked in position, and it is very convenient to adjust the angles and heights, angles can change from 10 to 27 degrees, raising your laptop up 2.83" to 5.19", providing you a better and a more comfortable posture when using the laptop Low Noise and Easy Operation - Even structured with 6 cooling fans, the noise level is 25dBA - 28 dBA, which is just like someone whispers around your ear. And the LCD display control panel allows you to adjust fan speed easily. There is no need to wrap your hands behind the cooler to operate, which is very troublesome 3 Modes and Extra USB Ports - Long pressing the ON/OFF button to adjust modes from 1, 2, 3, it\'s free to choose according to the situation. Extra USB ports allow you to connect a mouse, a keyboard. 2 small hidden anti-slip pads are helpful to protect your laptop, please remember to open them Widely Compatibility - The laptop fan cooling pad is compatible with all laptops from 13" to 15.6", and weighs 1.6LB, measures 14.56" x 10.43" x 1.26", portable for you to carry with your laptop.',
 'Raymate Bluetooth Speakers, HiFi Stereo Sound with DSP, 30W IPX7 Waterproof Speaker Wireless Bluetooth-V5.0, 1000mins Playtime, Portable Speaker for Home, Outdoor, Party 🎶HiFi Sound: With proven audio processing DSP chip technology, 30W dual speaker drivers and a more powerful amplifier module, the portable speakers delivers even, Balanced Sound Without Distortion. 🧱Integrated structure: With IPX7 Waterproof Speakers protection against rain, dust, snow and splashes, you can enjoy music in the pool, beach, park, bathroom and beyond.Comes with a dirt and corrosion resistant portable silicone protective sleeve. ✨Simple And Stylish: This is a speaker with a golden ratio rectangular body, combined with the purest colors, perfect for a variety of venues. 🔋Extended Battery Life: 3600mAh high-capacity battery provides you with more than 1000mins of play time.This speaker uses a more stable charging port - type C port, which greatly saves your waiting time. Note: We provide a 180 day warranty service and a 24-hour customer service response service.',
 "iPhone Charger Cord [Apple MFi Certified] Lightning Cable 1m/3.3FT Fast Charging High Speed Data Sync USB Cable Compatible with iPhone 14/13/12/11 Pro Max/XS MAX/XR/XS/X/8/7/Plus/6S iPad [Fast Charging & Sync] - iPhone Charger Cord Max 2.4 output current, high quality copper wire, improve charging and data transfer speed of iPhone charging cable. iPhone Lightning Cable ensures faster charging time and keeps your device safer. [Perfect comptibility] - iPhone lightning cables compatible with iPhone 14/14 Plus/14 Pro/14 Pro Max/iPhone 13/13 mini/13 Pro/13 Pro Max/12/12 mini/12 Pro/12 Pro Max/11/11 Pro/11 Pro Max/SE 2/XS/XS Max/XR/X/8Plus/8/7Plus/7/6s Plus/6s/6 Plus/6/5s/5c,iPad,AirPods [MFi Certified] - The lightning cable has an original lightning chip inside. Make sure it's compatible with your iPhone and charges your device safely. Enjoy fast data transfer, sync and charging. [Superior Durability] - iPhone lightning cable are made of top quality materials and coated with premium TPE. Passed 10,000 flex tests and won't get tangled for extra protection and durability. [What you get?] - 1x 3ft Mfi Certified iPhone Charging Cable. If you have any quality problems with our products, please feel free to contact us. We provide 24/7 customer support",
 'Skovlys Avocado Stickers for Water Bottles,Vinyl Waterproof Stickers for Water Bottle,50 Pcs Waterproof Vinyl Stickers for Water Bottle, Laptop, Phone Case, Guitaromputer,Phone,Guitar 🥑Avocado Stickers Pack,50pcs each pack, 50pcs no-duplicate stickers,2.5-3.5 inch each pcs 🥑3-layer structure, the surface layer is made of waterproof and scratch-resistant material, the printing layer is made of UV 7-color printing with bright colors, and the primer is made of PVC non-marking removable glue 🥑Our assortment of graffiti decals is your best choice when choosing a gift for your friends, kids. These creative patches will be the perfect present to make a cool room or for DIY decoration 🥑Stick them and use them for your Laptops, Skateboards, Luggage, Cars, Bikes, Bicycles, Bedroom, Travel Case, Bicycle, Motorcycle, Snowboard, PS4, XBOX ONE, etc.Guitar 🥑We are 100% guaranteed that you are completely satisfied with your product or receive your refund. We Partnered with Amazon FBA to give you the highest quality Amazon Prime shipping and hassle free returns.',
 '12 13 13.3 14 15.4 15.6 Inches Laptop Skin Sticker Decal Universal Netbook Skin Sticker | Need to Cut,Easy to Apply, Remove and Change Styles (Morning Glory) 100% Brand New and High Quality. Our laptop skins 15.6 inch，laptop skins 15.6 inch Fits up to 12.1"-15.6" laptops.High Resolution Printing. Flexible Film Helps Protect the Laptop Surface From Scratches & Smudges. We\'ve Made The Best Laptop Skin Sticker Decal Available and in a Variety of Wonderful Colors,PVC_Removable Layer & Paper layer; Three films aret of Our Way to Make Sure You are 100% Satisfied. Easy to Remove and Reuse .Will Last For Years and Won\'t Fade, Three Films are Included,one For the Back Side of The LCD Screen and Two For the Sides of the Touch Pad. About 38.0cm(15.0 inch) x 27.0cm( 10.6 inch);Compatible with :Most 12" ~ 15.6" wide Screen Notebook. The Sticker is Only One Size,You Maybe Need to Cut by Yourself to Fit Your Laptop. This is a No-Risk Purchase.If you have any questions for it ,No Hassle Refund Guaranteed.It can be a Sweet Gift Idea for Your Loved ones. We Will Go Out of Our Way to Make Sure You are 100% Satisfied.',
 'Geiomoo Silicone Case Compatible with Anker Soundcore Sport X10, Protective Cover with Carabiner (Black) Perfectly matches with Anker Soundcore Sport X10 Made of high quality soft silicone, scratch proof, shock proof and durable Carabiner is included to improve the practicality 360° all-round protection Easy to install',
 'TP-Link TL-SM331T | 1000Base-T RJ45 SFP Module | 1.25G Copper SFP Transceiver | SFP to Ethernet | Plug and Play | Hot Pluggable | Up to 100m distance | | Durable Metal Casing | Versatile Compatibility 【SFP to RJ45 1000Base-T Copper SFP】Transmit data seamlessly up to 100 meters between your SFP interface and the copper gigabit port. 【Wide Compatibility】Compatible with most fiber switches, media converters, routers or other fiber optic equipments with SFP ports, TL-SM331T provides additional copper cable connections for peace of mind. 【Easy for deployment】Plug and Play with no software installation or configuration/technician needed. 【Durable Metal Casing】Ensures strength and reliability for a long time, maintaining a stable connection in a wide range of environments. 【Hot Pluggable】Plug in or remove your SFP module without needing to shutdown your network. Hot swap-ability ensures your network always stays up.',
 'Fire HD 8 & HD 8 Plus Tablet Case for Kids (Only 12th Gen, 2022 Release) - DJ&RPPQ Lightweight Shockproof Cover with Handle Stand for Kindle Fire HD 8 Kids Tablet & Kids Pro Tablet - Blue Designed for Amazon All-New Kindle Fire HD 8 & Fire HD 8 Plus Tablet, Fire HD 8 Kids tablet & Fire HD 8 Kids Pro tablet (12th Generation 2022 Release), NOT fit for other models. Cutouts for clear access to all Amazon Kindle Fire HD 8 Plus / Fire HD 8 Tablet(12TH Generation, 2022Release) / Fire HD 8 Kids Pro 2022Tablet buttons, ports, speakers and rear-camera. Raised screen bezel edges for extra protection when fall. Kindle fire 8 case made with dense heavy duty EVA foam, Material can withstand considerable wear and tear and provide extreme shock protection.Super light weight and durable hazard free safe material perfect for kids and grownups alike. Built-in Kickstand- Designed with a foldable kick-stand on the back of the case, allows you to set up multiple angles and gives you the hands-free convenience when watching videos and movies. All-New Kindle Fire HD 8/8 plus Tablet case x 1.(The tablet is not included, and NO screen protector included); About customer service: Any questions please feel free to contact us and we will reply as soon as possible within 24 hours.',
 'Wekily Bluetooth 5.3 Headphones, Wireless Earbuds with 40H Playtimes Charge Case, Deep Bass, IPX7 Waterproof Running Earphones with 4-Mic Clear Call, LED Display, in Ear Headphones for Work/Gym Excellent Sound Quality: Wireless earbuds adopte graphene drivers and a polymer composite diaphragm carrying an AAC/SBC audio decoder, resulting in up to 43% bass enhancement. Audio technology is losslessly transmitted for a clearer stereo sound from the headphones. 40Hrs Cycle Playtimes: The 400mAh charging case has a playtime of 35 hours and the wireless headphones have a single playtime of 5hours of music. Quick charge in 10 minutes, 1 hour of use. In case of emergency. Bluetooth 5.3 Technology: The wireless headphones adopt bluetooth 5.3 chip, low battery consumption, fast transmission speed, and stable connection range up to 18m. Clear Call: Bluetooth earbuds adopt 4-microphone ENC reduction technology, combined with 13mm speakers, Making call is still very clear in public or gym environments. IPX7 Waterproof: Wireless sports earphones use nano-coating technology, waterproof and sweat-proof have passed the IPX7 standard, which is very suitable for your daily use.',
 "seenda Wired Mouse - USB Computer Mouse Wired with RGB Backlit Optical LED Mouse with Attached USB Cord for Laptops Notebooks Chromebook - Rose Gold Play in A Colorful Way -- A optical wired computer mouse featuring with rainbow colored changing light around the base of the mouse, you can choose how they are displayed as well as the ability to turn the colors off when you're not using it Plug & Play Wired Mouse -- Plug it to your computers and and it's been working ever since, with no issues or need to change settings. The smooth tracking, quiet, soft-touch buttons and wheels would be added features Sleek & Comfortable Shape -- This computer mouse does all that it needs in a comfortable shape and size, fits well for both small hands and big hands. It has a long enough cord to reach your computer easily Responsive & Accurate Click -- The optical response to the computer its very good, moving cursors, scrolling pages makes seamless efforts in using this mouse Universal Compatibility -- Works with Notebook, Computer, PC, Laptop,Chromebook with USB port, running on Windows XP/Vista/7/8/10 Mac OS X 10.4 etc.【Notice:This product is not compatible with macbook pro or other laptops which only have type c ports】",
 "MUSICOZY Bluetooth 5.3 Headband Headphones Built-in ENC Mic, Environmental Noise Reduction Earbuds Earphones for Sports Workout Calling Gaming Running for Women Men Cool Gadgets Elevate Your Audio Experience: Immerse yourself in flawless sound with our Bluetooth 5.3 Sports Headband, offering superior audio quality and minimal lag for an unrivaled listening journey. Uninterrupted Conversations: Don't let noise disrupt your connections! Our Bluetooth 5.3 ENC Sports Headband is designed to keep you seamlessly connected in any environment. Thanks to our advanced ENC technology, external noise is no match for this innovative headband. The ENC feature actively analyzes and suppresses background noise, providing you with crystal-clear calls and hassle-free communication, even in the busiest and noisiest surroundings. Ultimate Comfort, Unmatched Performance: Embrace hours of comfort with our skin-friendly, breathable fabric, and experience excellent sweat absorption during workouts, allowing you to focus on achieving your goals. Power That Lasts: Powered by a high-capacity 180mAh pure cobalt battery, our headband boasts an impressive 20+ hours of playtime on a single charge. With a charging time of only 2 hours, you'll be ready to enjoy extended audio sessions effortlessly. Versatility Redefined: Take control of your audio and communication experience with our cutting-edge sports headband. Elevate every moment with unparalleled clarity, convenience, and immersive sound. Whether you're at work, hitting the gym, or unwinding with music or podcasts, our headband is the perfect companion for all your activities. Additionally, it makes an ideal gift, offering a unique and practical present for your loved ones.",
 'Shechane AirPods 3 Case Cover 2021, Soft Leather Airpod Case with Strap Compatible with Airpod 3rd Generation, Supports Wireless Charging. (Black) 【Compatible with Airpods 3 case】: Specially designed for Airpod 3rd generation, not applicable for AirPods 1st, AirPods 2nd generation and AirPods Pro. 【Premium Material】: Made of high-quality genuine leather, Shechane AirPods 3 cases have unique natural texture and are soft, durable, delicate and stylish. 【Precise Design】: Precise cut-out ensures easy put-in and take-out of the charging case. And the accurate cut-out on the bottom supports USB charging as well as Wireless Charging. 【Full Protection】: Full-body covered soft leather and strong snap closure provide maximum protection for your Airpod 3 from dust, moisture, scratches ,drops and shocks. 【Easy to carry】: Strongly sewn with a leather strap, Shechane airpod 3 case can be hung on a handbag, backpack, or a key chain, or even on your wrist. Never need to worry breakage of the leather strap, if compared with those hung on a metal chain.',

In [25]:
embeddings = get_embeddings_batch(text_for_embedding)

In [26]:
len(embeddings)

50

In [27]:
pointstructs = []
counter = 1

for embedding, data in zip(embeddings, data_to_embed):
    pointstructs.append(
        PointStruct(
            id=counter,
            vector={
                "text-embedding-3-small": embedding,
                "bm25": Document(
                    text=data["preprocessed_description"],
                    model="qdrant/bm25"
                )
            },
            payload=data
        )
    )
    counter += 1

In [28]:
pointstructs[0].vector

{'text-embedding-3-small': [0.035614013671875,
  0.0220947265625,
  -0.041412353515625,
  -0.0002410411834716797,
  -0.0084381103515625,
  -0.005153656005859375,
  -0.01128387451171875,
  -0.029296875,
  0.06805419921875,
  -0.01239013671875,
  0.00494384765625,
  0.00739288330078125,
  -0.06622314453125,
  0.045867919921875,
  0.0045318603515625,
  -0.01537322998046875,
  -0.02276611328125,
  0.005382537841796875,
  -0.0194091796875,
  0.0284423828125,
  0.03558349609375,
  0.0303192138671875,
  -0.0078582763671875,
  -0.00029206275939941406,
  -0.0006275177001953125,
  -0.002140045166015625,
  0.031829833984375,
  0.0513916015625,
  0.022369384765625,
  -0.043792724609375,
  -0.032196044921875,
  -0.0266876220703125,
  -0.02093505859375,
  -0.042510986328125,
  -0.0297698974609375,
  0.00405120849609375,
  -0.0305938720703125,
  -0.05157470703125,
  -0.01238250732421875,
  -0.0058746337890625,
  0.01904296875,
  -0.047576904296875,
  0.0230865478515625,
  0.02239990234375,
  0.0293731689453125,
  -0.017303466796875,
  -0.03662109375,
  0.048095703125,
  0.01806640625,
  0.0030460357666015625,
  0.00937652587890625,
  0.054931640625,
  -0.04345703125,
  -0.008941650390625,
  0.0227813720703125,
  0.0023403167724609375,
  0.0296630859375,
  0.005542755126953125,
  0.033935546875,
  -0.0032482147216796875,
  -0.00870513916015625,
  -0.06976318359375,
  0.01094818115234375,
  -0.0235748291015625,
  -0.0201263427734375,
  0.030792236328125,
  -0.015960693359375,
  0.0116119384765625,
  -0.0293731689453125,
  0.00862884521484375,
  0.0013065338134765625,
  -0.0162811279296875,
  0.0298614501953125,
  -0.032989501953125,
  0.021759033203125,
  -0.0013399124145507812,
  0.0457763671875,
  -0.0053863525390625,
  0.0308074951171875,
  0.048095703125,
  -0.0286407470703125,
  0.0260772705078125,
  -0.025390625,
  0.023834228515625,
  -0.0179443359375,
  -0.0186767578125,
  -0.00405120849609375,
  0.0221405029296875,
  -0.029449462890625,
  -0.015289306640625,
  -0.004791259765625,
  0.0088348388671875,
  -0.0057220458984375,
  -0.00998687744140625,
  -0.022003173828125,
  0.0286865234375,
  0.00753021240234375,
  -0.058441162109375,
  0.045654296875,
  0.04132080078125,
  0.0123291015625,
  -0.05645751953125,
  -0.023651123046875,
  -0.01153564453125,
  0.035888671875,
  -0.0159759521484375,
  -0.026458740234375,
  -0.03704833984375,
  0.005352020263671875,
  0.01007080078125,
  0.0310516357421875,
  0.003643035888671875,
  -0.007762908935546875,
  0.01459503173828125,
  -0.0177001953125,
  -0.04046630859375,
  0.05230712890625,
  0.00949859619140625,
  0.00016927719116210938,
  -0.022125244140625,
  0.00513458251953125,
  0.0576171875,
  0.00984954833984375,
  0.0166015625,
  -0.01171875,
  -0.0276641845703125,
  -0.016448974609375,
  -0.012359619140625,
  -0.0022430419921875,
  0.0248565673828125,
  0.0192413330078125,
  -0.0243072509765625,
  0.08697509765625,
  -0.03997802734375,
  0.0059356689453125,
  -0.03753662109375,
  0.0019330978393554688,
  -0.006595611572265625,
  0.005863189697265625,
  0.0293731689453125,
  0.0089111328125,
  -0.0277252197265625,
  0.0166473388671875,
  0.005130767822265625,
  0.0401611328125,
  0.041168212890625,
  -0.0091094970703125,
  -0.03289794921875,
  -0.046875,
  0.0094146728515625,
  -0.00763702392578125,
  -0.045623779296875,
  -0.018646240234375,
  -0.01102447509765625,
  0.03607177734375,
  -0.01776123046875,
  0.06494140625,
  0.035247802734375,
  -0.0198516845703125,
  -0.045867919921875,
  0.01287078857421875,
  -0.030853271484375,
  -0.037811279296875,
  -0.055328369140625,
  0.021087646484375,
  0.038604736328125,
  0.0083465576171875,
  0.0244598388671875,
  -0.0537109375,
  0.01062774658203125,
  0.0185394287109375,
  -0.062744140625,
  0.041290283203125,
  0.00354766845703125,
  0.02911376953125,
  0.01317596435546875,
  0.00243377685546875,
  -0.0369873046875,
  0.01116180419921875,
  -0.0020809173583984375,
  0.00016164779663085938,
  -0.02093505859375,
  0.019683837890625,
  -0.04205322265625,
  -0.0065765380859375,
  -0.034393310546875,
  0.036376953125,
  -0.024169921875,
  -0.00762176513671875,
  -0.0017595291137695312,
  0.0119476318359375,
  -0.0022430419921875,
  -0.052459716796875,
  0.0170135498046875,
  0.01172637939453125,
  -0.01284027099609375,
  0.0023651123046875,
  -0.0175018310546875,
  -0.025848388671875,
  -0.026336669921875,
  -0.016815185546875,
  -0.00017261505126953125,
  0.00473785400390625,
  -0.0122833251953125,
  -0.056793212890625,
  -0.00043964385986328125,
  -0.033935546875,
  0.07635498046875,
  0.01421356201171875,
  0.0155487060546875,
  0.0178680419921875,
  -0.01142120361328125,
  -0.0019702911376953125,
  -0.001224517822265625,
  0.0023632049560546875,
  -0.033843994140625,
  0.003448486328125,
  0.044464111328125,
  0.0149078369140625,
  0.0110015869140625,
  -0.028289794921875,
  0.010955810546875,
  0.027740478515625,
  0.0187835693359375,
  -0.0194854736328125,
  -0.037872314453125,
  -0.0204620361328125,
  -0.034332275390625,
  0.0133056640625,
  -0.01099395751953125,
  0.0125579833984375,
  0.048919677734375,
  -0.017913818359375,
  -0.011138916015625,
  0.0191497802734375,
  0.0169677734375,
  0.0266571044921875,
  -0.03558349609375,
  -0.0089263916015625,
  -0.01154327392578125,
  -0.05535888671875,
  0.005939483642578125,
  0.0012359619140625,
  0.01678466796875,
  -0.001811981201171875,
  0.0019025802612304688,
  -0.0135650634765625,
  -0.01544189453125,
  -0.0245513916015625,
  0.03973388671875,
  0.05853271484375,
  0.0192413330078125,
  -0.03271484375,
  -0.016510009765625,
  0.044342041015625,
  0.0215911865234375,
  -0.0350341796875,
  0.0018472671508789062,
  0.004497528076171875,
  -0.00945281982421875,
  -0.047882080078125,
  -0.0028514862060546875,
  0.0031642913818359375,
  0.0262298583984375,
  0.0606689453125,
  -0.00439453125,
  0.00644683837890625,
  0.00579833984375,
  0.002162933349609375,
  -0.0168609619140625,
  0.032745361328125,
  0.0003108978271484375,
  -0.0048980712890625,
  -0.0054473876953125,
  -0.056610107421875,
  0.0288848876953125,
  0.0570068359375,
  0.0108489990234375,
  -0.055328369140625,
  -0.002490997314453125,
  0.006801605224609375,
  -0.03411865234375,
  0.037811279296875,
  0.0128936767578125,
  -0.033050537109375,
  0.0201416015625,
  0.0309295654296875,
  -0.01421356201171875,
  -0.018829345703125,
  -0.00865936279296875,
  -0.0172119140625,
  0.041351318359375,
  0.030059814453125,
  0.0252838134765625,
  0.0391845703125,
  0.045684814453125,
  -0.026702880859375,
  0.0254974365234375,
  -0.0298614501953125,
  -0.03839111328125,
  -0.01157379150390625,
  0.0574951171875,
  0.02593994140625,
  -0.0226593017578125,
  -0.0029754638671875,
  0.022705078125,
  -0.0189208984375,
  0.00872802734375,
  0.03985595703125,
  0.0026988983154296875,
  0.017578125,
  -0.01187896728515625,
  0.01953125,
  -0.02813720703125,
  -0.00213623046875,
  -0.00856781005859375,
  -0.00926971435546875,
  0.00313568115234375,
  0.0303192138671875,
  -0.035552978515625,
  0.00916290283203125,
  0.0311126708984375,
  0.0256500244140625,
  -0.01287078857421875,
  0.04315185546875,
  0.03759765625,
  0.01971435546875,
  -0.0206756591796875,
  -0.05810546875,
  -0.04339599609375,
  0.0289154052734375,
  -0.009735107421875,
  -0.00572967529296875,
  -0.034454345703125,
  -0.0193328857421875,
  -0.004253387451171875,
  -0.05535888671875,
  0.0194091796875,
  -0.11090087890625,
  0.0056304931640625,
  0.038482666015625,
  0.006290435791015625,
  -0.04327392578125,
  0.03631591796875,
  0.00231170654296875,
  -0.027069091796875,
  0.03265380859375,
  0.01519775390625,
  0.044036865234375,
  0.060882568359375,
  -0.0200958251953125,
  0.0211944580078125,
  0.02691650390625,
  -0.013702392578125,
  0.0290679931640625,
  0.016998291015625,
  0.044708251953125,
  0.0248260498046875,
  -0.041259765625,
  0.00598907470703125,
  0.0272064208984375,
  0.07177734375,
  -0.034027099609375,
  -0.0087127685546875,
  0.032501220703125,
  0.038909912109375,
  -0.04351806640625,
  0.01155853271484375,
  -0.025054931640625,
  -0.0188751220703125,
  0.022186279296875,
  0.034698486328125,
  0.019256591796875,
  0.003368377685546875,
  -0.030120849609375,
  0.003467559814453125,
  0.044830322265625,
  0.027313232421875,
  -0.0247039794921875,
  0.0259857177734375,
  0.051055908203125,
  0.0090484619140625,
  0.0311431884765625,
  -0.0196380615234375,
  -0.0007138252258300781,
  -0.0247802734375,
  -0.0223541259765625,
  0.0265960693359375,
  -0.003997802734375,
  -0.01617431640625,
  0.0230712890625,
  -0.02398681640625,
  0.0176849365234375,
  -0.0275115966796875,
  0.03668212890625,
  0.04449462890625,
  0.08135986328125,
  0.046142578125,
  0.01513671875,
  0.01241302490234375,
  0.0189056396484375,
  -0.0260467529296875,
  -0.0267486572265625,
  0.07757568359375,
  -0.0421142578125,
  0.0225677490234375,
  -0.01024627685546875,
  -0.046356201171875,
  0.0023441314697265625,
  -0.00583648681640625,
  -0.010650634765625,
  -0.054046630859375,
  0.017242431640625,
  0.0255889892578125,
  -0.02789306640625,
  -0.02587890625,
  -0.05865478515625,
  -0.021453857421875,
  0.0187835693359375,
  -0.0309295654296875,
  -0.04644775390625,
  -0.0281524658203125,
  -0.048004150390625,
  0.017364501953125,
  -0.0159759521484375,
  -0.0188140869140625,
  -0.0123748779296875,
  -0.05731201171875,
  0.0150146484375,
  -0.0413818359375,
  -0.01053619384765625,
  -0.04107666015625,
  -0.05145263671875,
  0.025390625,
  -0.048095703125,
  0.00882720947265625,
  -0.034088134765625,
  0.0028476715087890625,
  0.01898193359375,
  0.01085662841796875,
  0.00482940673828125,
  0.00342559814453125,
  0.01082611083984375,
  0.0323486328125,
  -0.035980224609375,
  0.02508544921875,
  -0.021575927734375,
  0.09130859375,
  -0.0760498046875,
  0.0198211669921875,
  -0.01239013671875,
  -0.08819580078125,
  -0.016937255859375,
  0.043914794921875,
  -0.06353759765625,
  -0.029144287109375,
  0.07794189453125,
  0.022674560546875,
  -0.040069580078125,
  -0.0261993408203125,
  0.014068603515625,
  0.01532745361328125,
  -0.04962158203125,
  -0.059051513671875,
  -0.0125274658203125,
  -0.0032558441162109375,
  0.0204925537109375,
  0.055419921875,
  0.0222320556640625,
  -0.03228759765625,
  -0.0005559921264648438,
  0.0283966064453125,
  -0.01020050048828125,
  0.020477294921875,
  -0.0168609619140625,
  -0.0022449493408203125,
  0.0479736328125,
  0.011566162109375,
  0.0096435546875,
  -0.007049560546875,
  -0.01220703125,
  -0.00882720947265625,
  -0.0237579345703125,
  -0.037506103515625,
  0.046600341796875,
  0.016021728515625,
  0.0098876953125,
  0.0288543701171875,
  -0.0374755859375,
  -0.00739288330078125,
  -0.03387451171875,
  -0.02166748046875,
  0.041473388671875,
  -0.007038116455078125,
  0.02880859375,
  -0.060272216796875,
  -0.03607177734375,
  -0.01100921630859375,
  -0.0109100341796875,
  0.060638427734375,
  -0.0104217529296875,
  0.04595947265625,
  -0.01922607421875,
  0.001007080078125,
  0.010833740234375,
  0.004566192626953125,
  0.0699462890625,
  0.0166168212890625,
  -0.0242919921875,
  0.0010461807250976562,
  -0.038482666015625,
  -0.0236358642578125,
  0.01222991943359375,
  0.0004291534423828125,
  -0.00565338134765625,
  0.01427459716796875,
  -0.03515625,
  0.0010223388671875,
  0.007030487060546875,
  -0.00948333740234375,
  -0.01172637939453125,
  0.01263427734375,
  0.020263671875,
  0.0135345458984375,
  -0.023651123046875,
  0.0178375244140625,
  -0.005847930908203125,
  -0.0797119140625,
  -0.0295257568359375,
  0.00701141357421875,
  -0.0254974365234375,
  0.0009274482727050781,
  -0.0141754150390625,
  0.00986480712890625,
  0.025177001953125,
  -0.03692626953125,
  -0.0029621124267578125,
  -0.0241546630859375,
  -0.0192718505859375,
  0.01605224609375,
  0.03460693359375,
  0.0060882568359375,
  -0.00799560546875,
  0.0073699951171875,
  0.006870269775390625,
  0.0139923095703125,
  -0.019378662109375,
  -0.01019287109375,
  0.0009250640869140625,
  -0.030120849609375,
  -0.00865936279296875,
  -0.021514892578125,
  0.022125244140625,
  -0.034698486328125,
  0.0121307373046875,
  0.0017108917236328125,
  0.004974365234375,
  -0.020416259765625,
  0.002605438232421875,
  -0.03033447265625,
  0.031890869140625,
  0.0283050537109375,
  -0.01367950439453125,
  0.01343536376953125,
  0.0284576416015625,
  -0.0104217529296875,
  -0.032928466796875,
  -0.0005469322204589844,
  -0.042755126953125,
  -0.0173187255859375,
  0.00841522216796875,
  -0.0025959014892578125,
  0.00201416015625,
  -0.01194000244140625,
  0.004459381103515625,
  0.0027408599853515625,
  -0.007568359375,
  -0.030029296875,
  -0.058502197265625,
  0.02178955078125,
  -0.015106201171875,
  0.022918701171875,
  -0.0011625289916992188,
  -0.00865936279296875,
  -0.0260009765625,
  -0.047454833984375,
  0.0158538818359375,
  -0.0164337158203125,
  0.045928955078125,
  0.0173797607421875,
  -0.01029205322265625,
  -0.0020160675048828125,
  0.003414154052734375,
  -0.00189208984375,
  -0.0369873046875,
  0.0081787109375,
  0.00885772705078125,
  0.04144287109375,
  0.03582763671875,
  -0.01348876953125,
  -0.017608642578125,
  -0.0025787353515625,
  -0.050140380859375,
  -0.001399993896484375,
  0.007144927978515625,
  -0.0179595947265625,
  0.0275726318359375,
  -0.0127716064453125,
  -0.036773681640625,
  0.014739990234375,
  -0.0236053466796875,
  0.00707244873046875,
  -0.0032253265380859375,
  -0.0096435546875,
  -0.024749755859375,
  0.0253143310546875,
  0.00379180908203125,
  -0.0233306884765625,
  0.005733489990234375,
  0.0251312255859375,
  -0.055145263671875,
  0.004718780517578125,
  -0.00374603271484375,
  -0.0153961181640625,
  0.0164337158203125,
  0.026702880859375,
  0.0006070137023925781,
  0.0029048919677734375,
  0.00865936279296875,
  -0.0108489990234375,
  -0.00490570068359375,
  0.02569580078125,
  0.0025501251220703125,
  -0.0036773681640625,
  -0.01398468017578125,
  0.00267791748046875,
  0.0296630859375,
  0.017059326171875,
  -0.019378662109375,
  -0.024505615234375,
  -0.010528564453125,
  0.012298583984375,
  0.05364990234375,
  -0.0313720703125,
  -0.08673095703125,
  0.03521728515625,
  -0.043304443359375,
  -0.0277862548828125,
  0.017822265625,
  -0.003192901611328125,
  -0.0260009765625,
  -0.020355224609375,
  0.0283355712890625,
  0.006011962890625,
  0.007266998291015625,
  0.01258087158203125,
  0.0136566162109375,
  -0.01708984375,
  -0.036834716796875,
  -0.00821685791015625,
  0.01360321044921875,
  -0.005657196044921875,
  -0.034332275390625,
  0.00865936279296875,
  -0.0264434814453125,
  0.0256805419921875,
  0.028350830078125,
  0.01360321044921875,
  -0.00748443603515625,
  0.0215606689453125,
  -0.0203399658203125,
  0.01428985595703125,
  -0.0231781005859375,
  -0.01861572265625,
  0.00417327880859375,
  -0.018341064453125,
  0.00421142578125,
  -0.0029048919677734375,
  0.02685546875,
  0.0487060546875,
  -0.01261138916015625,
  -0.02056884765625,
  -0.021636962890625,
  -0.01406097412109375,
  -0.01325225830078125,
  0.0069580078125,
  0.01313018798828125,
  0.0046844482421875,
  -0.0114593505859375,
  0.009521484375,
  0.0260467529296875,
  0.0360107421875,
  0.00676727294921875,
  0.004955291748046875,
  -0.037811279296875,
  0.0079193115234375,
  -0.01239013671875,
  0.0141143798828125,
  0.0286407470703125,
  -0.01531982421875,
  0.0135498046875,
  0.0169677734375,
  0.0035877227783203125,
  0.0333251953125,
  -0.053924560546875,
  0.0029850006103515625,
  -0.0090789794921875,
  -0.026702880859375,
  -0.01151275634765625,
  0.010284423828125,
  0.005706787109375,
  0.0251617431640625,
  -0.04327392578125,
  0.025543212890625,
  0.020263671875,
  -0.0258941650390625,
  0.00917816162109375,
  -0.00199127197265625,
  0.00974273681640625,
  -0.03668212890625,
  0.011138916015625,
  0.0247650146484375,
  -0.0160980224609375,
  -0.0298309326171875,
  0.0288848876953125,
  -0.0231170654296875,
  -0.026763916015625,
  -0.04290771484375,
  -0.0236968994140625,
  0.003391265869140625,
  0.020721435546875,
  -0.002227783203125,
  0.0034027099609375,
  -0.0196990966796875,
  -0.0229644775390625,
  0.0298614501953125,
  -0.01483917236328125,
  -0.02716064453125,
  0.004421234130859375,
  -0.058319091796875,
  -0.04522705078125,
  0.01503753662109375,
  0.0035724639892578125,
  0.011383056640625,
  -0.002559661865234375,
  0.0246124267578125,
  0.0164337158203125,
  -0.0211334228515625,
  -0.031463623046875,
  -0.00545501708984375,
  -0.04925537109375,
  0.006023406982421875,
  0.058135986328125,
  -0.0157623291015625,
  -0.036834716796875,
  -0.03704833984375,
  0.00852203369140625,
  0.044708251953125,
  -0.01470184326171875,
  -0.01451873779296875,
  -0.012969970703125,
  -0.00823974609375,
  -0.0091094970703125,
  0.0159759521484375,
  -0.02142333984375,
  -0.0216217041015625,
  -0.059234619140625,
  -0.0230255126953125,
  0.0018472671508789062,
  0.013153076171875,
  -0.0013017654418945312,
  0.004421234130859375,
  -0.00482940673828125,
  0.0019626617431640625,
  -0.0129241943359375,
  0.028228759765625,
  0.00707244873046875,
  -0.002948760986328125,
  0.0390625,
  -0.001758575439453125,
  0.033203125,
  -0.0380859375,
  -0.004871368408203125,
  -0.018402099609375,
  -0.01078033447265625,
  -0.035247802734375,
  0.0294189453125,
  0.0374755859375,
  -0.01534271240234375,
  -0.0233001708984375,
  0.0048675537109375,
  -0.019317626953125,
  -0.0034923553466796875,
  0.01457977294921875,
  -0.015838623046875,
  0.0132293701171875,
  0.0286102294921875,
  -0.00445556640625,
  0.01324462890625,
  0.030792236328125,
  0.012481689453125,
  -0.0244140625,
  0.0103302001953125,
  0.00015234947204589844,
  0.004817962646484375,
  0.052276611328125,
  -0.0233001708984375,
  -0.019775390625,
  -0.002105712890625,
  -0.04461669921875,
  -0.015960693359375,
  -0.00374603271484375,
  0.01424407958984375,
  -0.008636474609375,
  0.00499725341796875,
  0.060028076171875,
  0.006839752197265625,
  0.00750732421875,
  -0.02215576171875,
  -0.0153656005859375,
  -0.0150146484375,
  0.0085296630859375,
  -0.00525665283203125,
  -0.0172119140625,
  -0.0052947998046875,
  -0.00037360191345214844,
  -0.0482177734375,
  0.028289794921875,
  0.0031223297119140625,
  -0.036163330078125,
  0.034332275390625,
  -0.0139923095703125,
  0.0190582275390625,
  -0.00344085693359375,
  -0.001934051513671875,
  0.0150299072265625,
  -0.03009033203125,
  -0.00949859619140625,
  -0.0286865234375,
  -0.034088134765625,
  0.0070953369140625,
  -0.059051513671875,
  0.003154754638671875,
  -0.0032100677490234375,
  -0.003681182861328125,
  -0.04736328125,
  -0.061187744140625,
  0.0245208740234375,
  -0.007068634033203125,
  0.00896453857421875,
  -0.0010318756103515625,
  0.0011377334594726562,
  0.0162506103515625,
  -0.013458251953125,
  0.03375244140625,
  0.01019287109375,
  -0.0272064208984375,
  0.01105499267578125,
  0.01058197021484375,
  -0.0117645263671875,
  -0.029754638671875,
  0.035919189453125,
  0.02593994140625,
  -0.0294189453125,
  -0.0015106201171875,
  -0.0192108154296875,
  -0.05157470703125,
  -0.01079559326171875,
  0.033721923828125,
  0.0243988037109375,
  0.00911712646484375,
  -0.0184478759765625,
  -0.0307464599609375,
  -0.05419921875,
  -0.00669097900390625,
  0.017547607421875,
  -0.00884246826171875,
  0.030242919921875,
  -0.0131988525390625,
  -0.033294677734375,
  -0.05389404296875,
  0.02069091796875,
  0.003734588623046875,
  0.0114898681640625,
  -0.0167999267578125,
  0.03265380859375,
  -0.0094451904296875,
  0.0177001953125,
  -0.0014019012451171875,
  -0.0022449493408203125,
  -0.0204925537109375,
  0.0026760101318359375,
  0.03143310546875,
  -0.03558349609375,
  0.00362396240234375,
  -0.0150146484375,
  -0.023223876953125,
  0.0312042236328125,
  0.018524169921875,
  -0.0198974609375,
  0.0011377334594726562,
  0.00722503662109375,
  0.0036830902099609375,
  0.0016651153564453125,
  -0.022430419921875,
  0.0056304931640625,
  -0.0287933349609375,
  -0.00811004638671875,
  -0.0285797119140625,

In [29]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-hybrid-search",
    points=pointstructs,
    wait=True
)

UpdateResult(operation_id=3, status=<UpdateStatus.COMPLETED: 'completed'>)

### Hybrid Search

In [39]:
def retrieve_data_hybrid(query, k=10):
    query_embedding = get_embeddings_batch(query)[0]

    #hybrid retrieval
    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-hybrid-search",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                limit=k
            ),
            Prefetch(
                query=Document(
                    text=query,
                    model="qdrant/bm25"
                ),
                using="bm25",
                limit=k
            )
        ],
        query=RrfQuery(rrf=Rrf(weights=[0.4, 0.6])),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []
    retrieved_context_ratings = []

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_description"])
        similarity_scores.append(result.score)
        retrieved_context_ratings.append(result.payload["average_rating"])

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
        "retrieved_context_ratings": retrieved_context_ratings
    }

In [41]:
results = retrieve_data_hybrid("What are some available tablets?", k=20)

In [42]:
results

{'retrieved_context_ids': ['B0BG6TMXDD',
  'B0BBF2VC6X',
  'B0C9ZWCZ99',
  'B0B5LW6277',
  'B0BYRWPV86',
  'B0C9QZS95R',
  'B09WCT9S1R',
  'B0CF57H28T',
  'B0C8S6BBY9',
  'B0BM9THPDQ',
  'B09QGRRY7G',
  'B0CH8DRD6K',
  'B09YHG2Z7F',
  'B09P4QW5Y2',
  'B09KQP2H7N',
  'B09PTX6461',
  'B0BB6TFQ22',
  'B09V2Y1TQB',
  'B0BM657X74',
  'B0BMFYWK6T'],
 'retrieved_context': ['Fire HD 8 & HD 8 Plus Tablet Case for Kids (Only 12th Gen, 2022 Release) - DJ&RPPQ Lightweight Shockproof Cover with Handle Stand for Kindle Fire HD 8 Kids Tablet & Kids Pro Tablet - Blue Designed for Amazon All-New Kindle Fire HD 8 & Fire HD 8 Plus Tablet, Fire HD 8 Kids tablet & Fire HD 8 Kids Pro tablet (12th Generation 2022 Release), NOT fit for other models. Cutouts for clear access to all Amazon Kindle Fire HD 8 Plus / Fire HD 8 Tablet(12TH Generation, 2022Release) / Fire HD 8 Kids Pro 2022Tablet buttons, ports, speakers and rear-camera. Raised screen bezel edges for extra protection when fall. Kindle fire 8 case made with dense heavy duty EVA foam, Material can withstand considerable wear and tear and provide extreme shock protection.Super light weight and durable hazard free safe material perfect for kids and grownups alike. Built-in Kickstand- Designed with a foldable kick-stand on the back of the case, allows you to set up multiple angles and gives you the hands-free convenience when watching videos and movies. All-New Kindle Fire HD 8/8 plus Tablet case x 1.(The tablet is not included, and NO screen protector included); About customer service: Any questions please feel free to contact us and we will reply as soon as possible within 24 hours.',
  'Volkano Ninja Kids Earphones for Boys with Carry Case and Keyring - 3.5MM Stereo Jack - Wired Earbuds with Safe Volume 85dB - Earbuds for Kids for School for Online Learning/Travel/Tablet - Red/Blue HEARING PROTECTION: Made not just to look cool, but to be safe too. These kids\' earbuds with case limit their sound intensity to 85db to protect your kid\'s ears from discomfort during extended periods of listening to music. These wired earbuds provide a noise-isolating effect that removes external ambient sounds. MINI BAG FOR EARPHONES: This pouch may look small, but it\'s enough to store earphones for kids and their accessories, making it perfect for small toys as well! This mini bag can be carried in your child\'s hands with no trouble and has a zippered closure that prevents the bag\'s contents from spilling. The carry case has a soft interior and a sewn-in mesh side pocket for storing the earphones, in addition to 3 sets of earphone caps (S/M /L). CUTE DESIGNS: These 4ft earphones with mic have a colorful earbud exterior with a reliable built-in "Pause/Play" button for easy sound control on one side, an earphone clip that can be securely attached to any shirt, and a convenient little bag for carrying around the kids earphones! Available in an assortment of colors and cute designs: Ninja, Bulldog on Skateboard, Jet, and Space. WONDERFUL GIFT FOR KIDS: These adorable earphones are an excellent gift for any kid. They come in various colors and designs, and they even come with a cute carrying case! Plus, each pair comes with several different-sized earbud tips, so you can find the perfect fit for your little one. These are a fantastic option if you\'re looking for earphones for laptop or earphones for school kids that your kid can use. OUR PROMISE TO YOU: At Volkano, we take pride in providing our customers with products that are designed to last, give you endless entertainment and look amazing. These beautifully-designed earbuds for kids are no different! They feature immersive sound, a snug fit, media control, and other amazing highlights. We are committed to providing hassle-free assistance and immediate response whenever questions arise.',
  'HP 15.6" HD Busienss Laptop Newest, 6-core AMD Ryzen 5 5500U(up to 4.0GHz), 8GB RAM, 256GB SSD, USB-A&C, WiFi, Fast Charge, Windows 11 + GM Accessory 【15.6" HD micro-edge Display】Revolutionize your display and see more of what you love with this slim bezel design that maximizes your viewing area foor an immersive multimedia experience. 【AMD Ryzen 5 5500U Mobile Processor】Create. Play. Work. Educate. Entertain. The possibilities are infinite. Be anywhere, go anywhere. Powers ultrathin notebooks that offer supreme performance, astonishing battery life, and modern features you need on-the-go. 【Upgraded to 8GB system memory for advanced multitasking】Substantial high-bandwidth RAM to smoothly run your games and photo and video-editing applications, as well as multiple programs and browser tabs all at once. 【Upgraded to 256GB SSD Storage】Boot up in seconds, get to files faster, and have room for loads of files with the lightning-quick solid state drive. 【Windows 11 Home】Windows 11 is the place to think, express, and create in a natural way. 2 x USB-A; 1 x USB-C; 1XHDMI.',
  'Sony 85 Inch 4K Ultra HD TV X90K Series:BRAVIA XR LED Smart Google TV, Dolby Vision HDR, Exclusive Features for PS 5 XR85X90K-2022 w/HT-A5000 5.1.2ch Dolby Atmos Sound Bar Surround Home Theater INTELLIGENT TV PROCESSING – The Cognitive Processor XR understands how humans see to deliver intense contrast with deep blacks, high peak brightness, and natural colors. PERFECT FOR PLAYSTATION 5 – Take your gaming to the next level with input lag as low as 8.5ms and BRAVIA XR exclusive features for the PlayStation 5 – Auto HDR Tone Mapping & Auto Genre Picture Switch. Fully enjoy the thrill of Dolby Atmos and DTS:X with Vertical Surround Engine, S-Force Pro Front Surround and 360 Spatial Sound Mapping 360 Spatial Sound that adapts to your environment available with optional rear speakers',
  "10.2 Inch iPad Case Fit iPad 9th Generation 2021/ iPad 8th Generation 2020/ iPad 7th Generation 2019-360 Degree Rotating 10.2 iPad Case Cover for iPad 10.2 with Sleep Wake (Navy Blue) 【Perfect Fitting Your iPad 10.2】This ipad 9th generation case or ipad 8th generation or 7th generation case interchangeable covers precise cutouts for all ports and buttons gives you easy to access all ipad 10.2 original function, easy access to all features, jacks,camera and other ports. Easy installation & removal, no need to remove the your 10.2 inch ipad case while charging. 【Full Protection Your Apple ipad 10.2 】Shockproof hard back case to this ipad 10.2 case covers protect your ipad 10.2 inch tablet from shocks and drops. The 10.2 ipad case covers soft microfiber lining interior front cover to prevent screen scratch other daily damage. 7th generation or 8th generation or 9th generation ipad case 10.2'' elastic band holds ipad closed securely while on the go. 【ipad Case 10.2 Inch With 360 Degrees Feature 】 360 degrees rotating swivel allows the ipad to rotate both flexible vertically and horizontally while in the case. 10.2 ipad case rotating structure in the case in the case for flexible horizontal and vertical viewing. The ipad slot is only used to hold the ipad horizontally or vertically. It is not suitable for touching or tapping the ipad. 【Very Easy Installation 10.2'' ipad Case covers Design 】: Easily snaps 10.2 ipad into mount (simply snap on right side first, then left side). You will feel the pleasure of installing the ipad stand and happy use of ipad. 【iPad 10.2 inch Case Compatible Model】This ipad case covers designed for ipad 10.2 inch 9th generation (Model: A2602 / A2603 / A2604 / A2605), ipad 10.2 inch 8th generation (Model: A2270 / A2428 / A2429 / A2430), ipad 10.2 inch 7th generation (Model: A2197 / A2198 / A2200), Please confirm your ipad model before you order this ipad case.",
  'USB C to USB C Cable, INIU [6.6ft 100W PD 5A] Super Fast Charging Type C to Type C Cable, Nylon Braided USB-C Cord Phone Charger for Samsung S23/Ultra Note 20 iPad Pro MacBook Steam Deck LG Google etc ✅【From INIU--the SAFE Fast Charge Pro】 Experience the safest charging with over 38 million global users. At INIU, we use only the highest-grade materials, so we do have the confidence to provide an industry-leading 3 years warranty. ✅【Fuel Laptop Up to 58% Faster via New-Gen 100W】 The all-new 100W PD tech takes charging speed to the next level. Incredibly fast fuel your MacBook Pro 16” to 60% in just 45mins—that’s 58% faster than a 60W cable. ✅【2023 Upgrade 100W Charges All Devices Faster】 The next-level 100W USB C on both ends can assuredly power all your newest phones, tablets and laptops at a faster speed — fuels Samsung S22 Ultra to 89% in just 30mins, while other 60W and 3.1A cables can only up to 54% — notably knocks off 45mins of your waiting time. ✅【The Safest Fast Emark 2.0 Smart Chip】 Other 60W without Emark are prone to fires and explosions. In contrast, the latest Emark2.0 chip exclusive to 100W maximizes charging safety through auto-adjusting power, clearly a better option to eliminate battery overheating damage. ✅【20X Durable, Never Rupture & Break】 Exclusive FLYWEAVE braided nylon coat, plus flexible anti-rupture SR joints, build a cable that was still intact after the market’s most-tested 45,000+ bending test, but the other cables had broken. ✅【Even Wider Compatibility Than 60W】 With the powerful 100W output, it charges an even wider range of devices than those 60W cables, including all the USB C phones, tablets, and virtually any flagship notebooks, Switch and more. ✅【What You Get】 6.6ft USB-C to USB-C cable*1, cable strap*1, user manual*1, 30 days money back, INIU industry-leading 3-year warranty and lifetime technical support.',
  '12 13 13.3 14 15.4 15.6 Inches Laptop Skin Sticker Decal Universal Netbook Skin Sticker | Need to Cut,Easy to Apply, Remove and Change Styles (Morning Glory) 100% Brand New and High Quality. Our laptop skins 15.6 inch，laptop skins 15.6 inch Fits up to 12.1"-15.6" laptops.High Resolution Printing. Flexible Film Helps Protect the Laptop Surface From Scratches & Smudges. We\'ve Made The Best Laptop Skin Sticker Decal Available and in a Variety of Wonderful Colors,PVC_Removable Layer & Paper layer; Three films aret of Our Way to Make Sure You are 100% Satisfied. Easy to Remove and Reuse .Will Last For Years and Won\'t Fade, Three Films are Included,one For the Back Side of The LCD Screen and Two For the Sides of the Touch Pad. About 38.0cm(15.0 inch) x 27.0cm( 10.6 inch);Compatible with :Most 12" ~ 15.6" wide Screen Notebook. The Sticker is Only One Size,You Maybe Need to Cut by Yourself to Fit Your Laptop. This is a No-Risk Purchase.If you have any questions for it ,No Hassle Refund Guaranteed.It can be a Sweet Gift Idea for Your Loved ones. We Will Go Out of Our Way to Make Sure You are 100% Satisfied.',
  '1TB USB Flash Drives, NEIGHBOR Portable Thumb Drive 1TB USB Memory Stick, Metal 1000GB USB Drive High-Speed Waterproof Jump Drive for Data Storage and Transfer 【Reliable & Durable】The usb memory stick adopts Grade-A chips and high quality flash memory particles, safeguards your data and transfers your data seamlessly. Quicker heat dissipation permits longer service life. Suitable for storing digital data for school, business or daily usage. With Small size, these flash drives are readily available wherever you go. 【Excellent Compatibility】Ultra High Speed 1TB Flash Memory Stick is plug and play without any software installation; Simply insert the USB 3.0 Pen Drive 1000GB into the device to transfer and store data between the devices. The USB Flashdrives Supports Windows 7/8/10 / Vista / XP / Unix / 2000 / ME / NT Linux and Mac OS, and is compatible with USB 1.1, USB 2.0 and USB 3.0 ports. 【High Quality】USB Flash Drive 1TB features durable and rugged Metal housing body. The inside uses the most advanced imported smart chip, assembled through many complicated and strict processes. Therefore, it has excellent water resistance, magnetic resistance, high-temperature resistance, and X-ray resistance, thus ensuring that its service life far exceeds other similar products, which makes you store your data with more confidence. 【Powerful Storage Functions】USB Thumb Drive 1TB can transfer up to 204800 photos[10 megapixels]; 102400 MP3 audio files; 2560 minutes HD videos[1080P resolution] or 5120 minutes HD videos [720P resolution]. 1TB Flash Memory Stick is commonly used for storage, data backup and computer file transfer, it will meet your needs of daily use on work, school, home, and traveling for photos, music, videos, files storage and transfer. 【24 Hour Warm Customer Service】USB flash drive 1000GB widely use on personal use and meet your business needs in daily life.We always try our best to provide 100% customer satisfaction.Please click contact us if you have any quality issues.We are always here to address your problem in 24 hours.',
  "PRUNUS J-166 Portable Radio AM FM, Battery Operated with Tuning Light, Back Clip, Excellent Reception for Indoor & Outdoor Emergency Radio, FM Portable, Transistor 【Portable Design】You can hold mini radio by one hand. it's small enough to put it in emergency kit. This FM AM radio measures 69*128*28mm with weight only 119g (without batteries), close to the size of iPhone 7. More importantly, thanks to its back clip and lanyard, transistor radio is pretty easy to carry around whether it’s clipped to pocket or carried with lanyard. Now, take it for morning exercise, stroll or a break in park, together with a piece of brisk music or a great radio show. 【Easy to Use】 After busy work, sometimes it’s nice to take a nap with a simple battery radio. Designed with three control buttons - tuning knob, volume knob, band/power switch button, J-166 portable radio is quite easy to operate. The tuning indicator, on the other hand, reminds you of available radio stations. See, how simple it is. 【Excellent Signal Reception】FM: 87-108 MHz, AM:520-1730 kHz; I guess a small radio with excellent signal reception definitely can capture your heart, right? Our handheld radio is the right one. It’s not only equipped with 16.5 inch long 360° adjustable antenna, but built in advanced DSP chip. No matter which city or even a remote area you’re in, you can get the local stations easily. 【Perfect Sound quality】 With built-in magnetic speaker featured as clear sound playing, you could share the moment filled with various baseball games, talk shows, classical musics and news with your friends. Meanwhile, the music of one often speaks directly to one’s heart. So it’s fabulous to enjoy your favorite musics in your own world with plugging your earphones to 3.5mm earphone jack on the pocket radio am fm. 【Convenient Indicator】The AM/FM radio powered by 2*AA batteries (not included in package).The red battery indicator will tell you if the battery still has power and if it needs to be replaced. Also, when you are about to receive a station, the signal indicator will turn green, which will tell you that you need to adjust the knob amplitude less to help you find that station, very convenient.",
  'Cruise Power Strip Foldable Non Surge Protector with USB C Outlets 3.4A Total, Multi Plug Wall Socket, Cruise Essentials Accessories Must-Haves for Travel Ship, Home, Japan Applicable 🤩【Cruise Essentials】- a better power strip choice for cruise travel, no surge protector with USB C outlets, no extension cord, suitable for any form of travel, and also a plugs extender for home use. 👍【Folded Plug Easy to Carry】- The plug can be folded👏, convenient for travel. Small size, 3.5*2.9*1.2 inches does not take up space. Light Weight, only 150g, easy to carry without burden. 🤳【Convenient to Use】 - Light and small size, while maximizing the use of 3 ACs and 3 USBs at the same time, during travel. ✍This 1 to 6 plug extender can be converted from 2 prong and 3 prong, even suitable for traveling in Japan. 💯【Better Configuration】- Our multiple plug outlet increases the Type C port to meet the charging of more types of mobile phones, 3.4A current, different from 2.4A, the charging speed is 30% faster. 🎁【Cruise Accessories Must Haves】- Our brand promises：1. anyone who buys our cruise accessories and cannot take them on the cruise, informs the model and reason for the cruise, and can enjoy the free cruise power strip or return service 2. those who use our multi-plug outlet for less than 12 months and are damaged due to non-human reasons can enjoy free new one.',
  'WisaKey 13" RGB Ring Light with Stand and Phone Holder Tall 63", 218 LEDs Selfie Ring Light & Sunset Lamp with Desktop Tripod, 51 Colors Modes, 13 Dimming Levels for TikTok/Live Stream/Makeup/YouTube 【1-year worry-free guarantee】WisaKey Ring Lights come with a 30-day money-back guarantee & a 12-month product warranty. If you have any questions, please contact us, our experts will assist you within 24 hours. 【What You Get】13 inch ring light 10-piece set: 1 LED ring light, 1 sunset light, 1 tablet holder, 2 cell phone holders. 1 Bluetooth shutter ( compatible with iOS & Android systems), 1 floor tripod , 1 desktop tripod (can support ring light or sunset light), 1 ring light remote control, 1 sunset lamp remote control. 【51 Colors Modes & 218 LEDs】 This halo ring light with stand has 218 LED beads and 51 color modes: 1,3 basic lighting modes: (cool white, warm yellow & daylight) and 12 brightness levels range. 2,10 static RGB color modes and 13 levels of dimmer range. 3,38 dynamic RGB color modes. Over 200 color setting modes in total to meet every lighting need and show you at your best in the perfect light. 【Bluetooth shutter & USB Power Supply】The Bluetooth shutter allows you to easily take video or photos remotely within 15m, compatible with iOS and Android systems. The ringlight can support USB charging, the included USB cable is up to 2m, suitable for most devices that support USB ports, such as laptops, AC chargers, mobile power, etc. You can fill light, selfies, do makeup, participate in live streaming, video conference, Youtube, TikTok, etc. anytime and anywhere. 【Adjustable Desk/Floor Ring Lamp】Selfie ring light with tripod stands, floor tripod height can be extended to 63 \'\', desktop tripod height can be adjusted to 7.08 \'\'. Both are made of sturdier materials that are stable and will not tip over. Also comes with 2 phone holders and 1 tablet holder. You can freely adjust the position and angle of the holders to achieve horizontal and vertical shooting. It is the perfect choice for ring light kits. 【16 Colors Sunset Lamp】This RGB ring light set comes with a USB rechargeable sunset light, 16 RGB color options, and 4 gradient modes to create a variety of romantic atmospheres. It also has a wireless remote for easy remote operation. The sunset projection lamp can be used for home lighting, photo background, warm atmosphere, live broadcast, wedding atmosphere, gifts, night light, etc.',