# Agent that has multiple tools available

In [17]:
from dotenv import load_dotenv
load_dotenv("../../.env")


from pydantic import BaseModel
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode

from IPython.display import Image, display

from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import SystemMessage, HumanMessage, convert_to_openai_messages

from qdrant_client.http.models import MatchValue, FieldCondition, Filter
from qdrant_client.models import VectorParams, Distance, SparseVectorParams, Modifier, PayloadSchemaType, PointStruct, Document, Prefetch, RrfQuery, Rrf

import openai
from qdrant_client import QdrantClient
from langsmith import traceable, get_current_run_tree
import instructor
from pydantic import BaseModel, Field

from jinja2 import Template

from typing import Annotated, List, Any
from operator import add

from sentence_transformers import CrossEncoder

# persistence in multi turn conversations
from langgraph.checkpoint.postgres import PostgresSaver
import os

# creating new collection
import pandas as pd
import tiktoken

### Creating new Rating Qdrant collection

In [18]:
qdrant_client = QdrantClient(url="localhost:6333")

In [19]:
COLLECTION_NAME = "Amazon-reviews-collection-hybrid-search"

try:
    qdrant_client.create_collection(
        collection_name=COLLECTION_NAME,
        vectors_config={
            "text-embedding-3-small": VectorParams(size=1536, distance=Distance.COSINE),
        },
        sparse_vectors_config={
            "bm25": SparseVectorParams(modifier=Modifier.IDF),
        }
    )
except Exception as e:
    print(f"Collection probably already exists! Here is the error message:\n{e}")

Collection probably already exists! Here is the error message:
Unexpected Response: 409 (Conflict)
Raw response content:
b'{"status":{"error":"Wrong input: Collection `Amazon-reviews-collection-hybrid-search` already exists!"},"time":0.005195125}'

In [20]:
qdrant_client.create_payload_index(
    collection_name=COLLECTION_NAME,
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=6, status=<UpdateStatus.COMPLETED: 'completed'>)

In [21]:
### EMBEDDINGS ###
def get_embeddings_batch(text_list, model="text-embedding-3-small", batch_size=100):
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]

    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend(
            [embedding.embedding for embedding in response.data]
        )

        print(f"Batch #{counter}: {counter * batch_size} / {len(text_list)}")
        counter += 1

    return all_embeddings

In [22]:
# read the ratings dataset
df_reviews = pd.read_json("../../data/Electornics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [23]:
df_reviews.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,Camera & Photo,8x8ft Pink Rose Flower Theme Photography Backd...,4.5,358,"[ʚɞSize：8x8FT 2.4 m wide by 2.4 m tall,Item se...",[Details 1. The item color as the picture show...,38.90,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Avezano Brand Video', 'url': 'http...",XLL,"[Electronics, Camera & Photo, Lighting & Studi...",{'Package Dimensions': '10.94 x 9.57 x 1.97 in...,B08XQ8PS2J,NaN
1,Cell Phones & Accessories,Spigen Tempered Glass Screen Protector [GlasTR...,4.3,921,[Tempered glass durability rated at 9H hardnes...,[],32.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Gal Tab S8 Series Installation Gui...,Spigen,"[Electronics, Computers & Accessories, Tablet ...","{'Product Dimensions': '12.71""L x 8.07""W', 'It...",B09P5NQH7Q,NaN
2,Amazon Home,COLSUR【2023 Newest Bluetooth Speaker with Digi...,4.3,580,[【6 IN 1 Multifunctional Alarm Clock Design】- ...,[],56.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Digital Alarm Clock Radio with Blu...,COLSUR,"[Electronics, Home Audio, Compact Radios & Ste...","{'Brand': 'COLSUR', 'Color': 'Wooden', 'Displa...",B0B4JVPWMJ,NaN
3,Computers,Beelink Mini pc 10 Cores 12th Generation Intel...,4.4,263,[【12th Gen Intel i5 Ultra High-efficiency】Beel...,[],449.00,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'SEi12 i5-1235U 16+500GB', 'url': '...",Beelink,"[Electronics, Computers & Accessories, Compute...","{'Processor': '4.4 GHz core_i5', 'RAM': '16 GB...",B0C69CCSJW,NaN
4,All Electronics,ZOVITS U-Shuxian Wireless Earbuds Blutooth 5.3...,4.5,452,"[LED power display charging case, deep BASS, S...",[ZOVITS U-Shuxian Wireless Earbuds Lightweight],22.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': '30 Hrs of Playtime for this Price?...,ZOVITS,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '4.29 x 3.98 x 1.54 inc...,B0BFR3QPWR,NaN

In [24]:
len(df_reviews)

1000

In [25]:
# preprocess title and features
def preprocess_reviews_data(row):
    return f"{row['title']} {row["description"]}"

In [28]:
def count_tokens(text: str):
    encoding = tiktoken.encoding_for_model("text-embedding-3-small")
    return len(encoding.encode(text))

def count_tokens_row(row):
    return count_tokens(row["preprocessed_content"])

In [29]:
count_tokens("Hi")

1

In [30]:
df_reviews["preprocessed_content"] = df_reviews.apply(preprocess_reviews_data, axis=1)
df_reviews["token_count"] = df_reviews.apply(count_tokens_row, axis=1)

In [31]:
df_reviews.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,preprocessed_content,token_count
0,Camera & Photo,8x8ft Pink Rose Flower Theme Photography Backd...,4.5,358,"[ʚɞSize：8x8FT 2.4 m wide by 2.4 m tall,Item se...",[Details 1. The item color as the picture show...,38.90,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Avezano Brand Video', 'url': 'http...",XLL,"[Electronics, Camera & Photo, Lighting & Studi...",{'Package Dimensions': '10.94 x 9.57 x 1.97 in...,B08XQ8PS2J,NaN,8x8ft Pink Rose Flower Theme Photography Backd...,274
1,Cell Phones & Accessories,Spigen Tempered Glass Screen Protector [GlasTR...,4.3,921,[Tempered glass durability rated at 9H hardnes...,[],32.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Gal Tab S8 Series Installation Gui...,Spigen,"[Electronics, Computers & Accessories, Tablet ...","{'Product Dimensions': '12.71""L x 8.07""W', 'It...",B09P5NQH7Q,NaN,Spigen Tempered Glass Screen Protector [GlasTR...,32
2,Amazon Home,COLSUR【2023 Newest Bluetooth Speaker with Digi...,4.3,580,[【6 IN 1 Multifunctional Alarm Clock Design】- ...,[],56.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Digital Alarm Clock Radio with Blu...,COLSUR,"[Electronics, Home Audio, Compact Radios & Ste...","{'Brand': 'COLSUR', 'Color': 'Wooden', 'Displa...",B0B4JVPWMJ,NaN,COLSUR【2023 Newest Bluetooth Speaker with Digi...,45
3,Computers,Beelink Mini pc 10 Cores 12th Generation Intel...,4.4,263,[【12th Gen Intel i5 Ultra High-efficiency】Beel...,[],449.00,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'SEi12 i5-1235U 16+500GB', 'url': '...",Beelink,"[Electronics, Computers & Accessories, Compute...","{'Processor': '4.4 GHz core_i5', 'RAM': '16 GB...",B0C69CCSJW,NaN,Beelink Mini pc 10 Cores 12th Generation Intel...,77
4,All Electronics,ZOVITS U-Shuxian Wireless Earbuds Blutooth 5.3...,4.5,452,"[LED power display charging case, deep BASS, S...",[ZOVITS U-Shuxian Wireless Earbuds Lightweight],22.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': '30 Hrs of Playtime for this Price?...,ZOVITS,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '4.29 x 3.98 x 1.54 inc...,B0BFR3QPWR,NaN,ZOVITS U-Shuxian Wireless Earbuds Blutooth 5.3...,36

In [32]:
# filter out very long reviews
df_reviews = df_reviews[df_reviews["token_count"] < 8192]

In [33]:
len(df_reviews)

1000

In [36]:
# total token count to embed
total_tokens = df_reviews["token_count"].sum()
total_tokens

np.int64(92775)

In [38]:
total_cost = total_tokens * 0.00000002 #price per token for text-embedding-3-small in USD
print("Total cost to embed in USD:", total_cost)

Total cost to embed in USD: 0.0018555

In [39]:
data_to_embed = df_reviews[["preprocessed_content", "parent_asin"]].to_dict(orient="records")

In [40]:
data_to_embed

[{'preprocessed_content': "8x8ft Pink Rose Flower Theme Photography Backdrops 3D Pink Floral Newborn Kids Wedding Bridal Shower Photo Background Mother's Day Anniversary Ceremony Couple Photo Props Cake Table Banner ['Details 1. The item color as the picture shown. 2. Made of vinyl cloth. Which is lightweight, thin, easy to carry, durable and wrinkle . 3. May have some creases, but it can be removed. 4. Cannot be washed. 5. Can be folded, easy to place. 6. Non-reflective. 7. The package just have one piece of backdrop. How to remove wrinkles (1)Hang naturally for a few days, no problem. (2) Heat it with a steam iron on the back of item, if necessary, please iron the back surface with steam iron but not dry iron. Then it will be smooth again. Warm-tip Because of the difference between the monitor and the light, here is normal that a slight difference in the color. The picture is clear, realistic, stereo sense is strong. Applications range: It can be used at many situations, such as getting together occasion, weddings,work,graduation,Birthday, Party，home photography any big events or decorations etc. If you have any questions please contact us. We will reply you as soon as possible. Thanks!']",
  'parent_asin': 'B08XQ8PS2J'},
 {'preprocessed_content': 'Spigen Tempered Glass Screen Protector [GlasTR EZ FIT] Designed for Galaxy Tab S8 Ultra [9H Hardness/Case-Friendly] []',
  'parent_asin': 'B09P5NQH7Q'},
 {'preprocessed_content': 'COLSUR【2023 Newest Bluetooth Speaker with Digital Alarm Clock, Wireless Charger, FM Clock Radio, Adjustable LED Night Light, Dual Wireless Speakers,2500mAh Battery for Bedroom,Home, Adaptor (Wooden) []',
  'parent_asin': 'B0B4JVPWMJ'},
 {'preprocessed_content': 'Beelink Mini pc 10 Cores 12th Generation Intel i5-1235U(up to 4.4Ghz),TDP 55W 16G DDR4 3200Mhz，500GB M.2 NVMe Pcle 4.0 SSD Mini Desktop Computers, WiFi6, BT5.2, Dual HDMI Business Mini Computers []',
  'parent_asin': 'B0C69CCSJW'},
 {'preprocessed_content': "ZOVITS U-Shuxian Wireless Earbuds Blutooth 5.3 Headphones for iPhone ['ZOVITS U-Shuxian Wireless Earbuds Lightweight']",
  'parent_asin': 'B0BFR3QPWR'},
 {'preprocessed_content': 'SOOPII 100W 6.6ft USB C to USB C Cable Fast Charge, Nylon Braided Type-C Cable with LED Display for lPad Air/lPad Pro, MacBook Pro, Samsung Galaxy S21/S10/S9/Plus (Black) []',
  'parent_asin': 'B09V7VC1LB'},
 {'preprocessed_content': 'Shintop Cord Organizer, 6 Pack Black Charger Holder Cable Clips Wire Clips for Organizing Desk Nightstand Car Phone Charger []',
  'parent_asin': 'B0B752NSBC'},
 {'preprocessed_content': 'Pad []', 'parent_asin': 'B09RN3KN5C'},
 {'preprocessed_content': "ASUS E410 Intel Celeron N4020 4GB 64GB 14-Inch HD LED Win 10 Laptop (Star Black) ['More power, more security, and more ways to do it all. The Asus 14-inch laptop lets you adapt to anything your day has in store, without sacrificing power or security. With the power and versatility you want and a suite of cutting-edge security features you need, you can stay productive and protected like never before. Elevate your entertainment on a high-resolution, micro-edge display.', 'Superb Performance', 'With Intel Celeron N4020 Dual-Core Processor, 4GB RAM, 64GB storage capacity, and Integrated Intel Graphics, you can harness superb productivity power, and keep going with an amazing battery back-up.', 'Stunning Views', 'With a 14-inch HD LED display, all your entertainment and creative projects can shine. Edit photos and stream your media with perfect clarity.', 'Sleek Design', 'Easily take this thin and light PC from room to room or on the road. Take it anywhere and look sharp.', 'Specifications:', 'Intel Celeron N4020 Dual-Core Processor 1.1GHz Up to 2.8GHz', 'Intel Celeron N4020 Dual-Core Processor 1.1GHz Up to 2.8GHz', '4GB SDRAM', '4GB SDRAM', '64GB eMMC Storage', '64GB eMMC Storage', '14-inch HD LED Display (1366 x 768)', '14-inch HD LED Display (1366 x 768)', 'Integrated Intel Graphics', 'Integrated Intel Graphics', 'Webcam', 'Webcam', '2 USB Type-A', '2 USB Type-A', 'HDMI', 'HDMI', 'Card reader', 'Card reader', 'Wi-Fi 802.11', 'Wi-Fi 802.11', '1 headphone/microphone combo', '1 headphone/microphone combo', 'Stereo speakers', 'Stereo speakers', '3-cell Li-ion Battery', '3-cell Li-ion Battery', 'AC power adapter', 'AC power adapter', 'Windows 10', 'Windows 10']",
  'parent_asin': 'B09YRY6QCX'},
 {'preprocessed_content': "mygreen Electronics Travel Organizer, Electronic Accessories Case with Handle, Portable Tech Travel Gifts for Men Double Layer Cable Storage Bag for Cord, Charger, Ipad Mini Light Green ['Why Mygreen Travel Gadget Organizer Bag?', 'this case is ideal for storing and organizing gadgets of various sizes, such as cellphones, chargers, USB cables, earphones, SD cards, power banks and so on. Mesh pockets and elastic bands allow divisional storage and easy access to all of the electronics and accessories. Double layer design allows holding and securing all your essentials in one place. Mygreen Versatile Organizer is a top solution for small electronics, a must-have for daily life and travel.', 'Storage of Front Layer', '-1 large zipper pocket can fit quick access electronic device.', 'Storage of First Layer', '-1 large pockets with zipper can fit large cell phone like iphone 13/14 pro max etc -1 mesh pocket with zipper can fit portable hard drives, power banks, cameras and cellphones or small items such as USB cables, USB flash disk, MP3 player and other items. -7 elastic straps for organizing various cables, earphones, batteries chargers and more. -7 mesh elastic pockets can fit SD Card, Hard Drive -1 pen slot and 3 leather SD Card holders', 'Storage of Second Layer', '-1 large mesh pocket with with 2 elastic straps for ipad mini -1 mesh zipper pocket for storing cellphones, cards, keys and a little bit of cash. -1 spacious compartment with 4 detachable dividers, which can allow you to design the layouts as your need.', 'Take It Anywhere', '-Perfect for Traveling -This case makes the most efficient use of packing space inside your suitcase or bag.The lightweight handle design allows you to carry the bag anywhere.']",
  'parent_asin': 'B089LDYYPM'},
 {'preprocessed_content': 'MP3 Player with Bluetooth and WiFi, 4" Full Touch Screen MP4 MP3 Player with Spotify, Android Streaming Music Player with Pandora, Portable HiFi Sound Walkman Digital Audio Player with Speaker (White) []',
  'parent_asin': 'B0C4FF1967'},
 {'preprocessed_content': 'Jasput USB Splitter Cable,1 Male to 2 Female USB Extension Cable Connectors, Multiport USB Extender Hub,Charger & Data Transfer USB Y Splitter for Laptop,Car,Mac,TV,PC,Xbox One Series X/S,HDD,Phone []',
  'parent_asin': 'B09X9RM6FD'},
 {'preprocessed_content': 'YABER 2022 Upgrade 5G WiFi Bluetooth Projector, 1080P Full HD Supported Portable Projector with Tripod and Carrying Bag, Mini Movie Outdoor Projector Compatible with Smartphone,Laptop,HDMI, VGA,USB,AV []',
  'parent_asin': 'B0BDKS21DQ'},
 {'preprocessed_content': 'UGREEN 2 Pack USB Extension Cable, (10 FT+ 10 FT) USB Extender USB 3.0 Extension Cable Nylon Braided Compatible with Webcam, Camera, Phone, USB hub, Mouse, Keyboard, Printer, Hard Drive, Headset []',
  'parent_asin': 'B08HLZWM63'},
 {'preprocessed_content': 'Military Men Smart Watch(Answer/Make Calls), 2022 Newest Bluetooth Tactical Smart Watch for Android iPhone, IP68 Waterproof Outdoor Tough Rugged Fitness Tracker with AI Voice/Heart Rate/Sleep, Black []',
  'parent_asin': 'B0B2ZVX1GQ'},
 {'preprocessed_content': 'Basesailor USB C to USB C 100W Cable 10FT with USB A Adapter,Fast Charging PD Charger Cord Samsung Galaxy Z Flip Fold 3 4,S9 S10 S10E S23 S20 S21 S22,Note 10 20,A21 A22 A23,A31 A32 A33,A42,A51 A52 A53 []',
  'parent_asin': 'B0B6J78QZP'},
 {'preprocessed_content': 'Aisizon Air Conduction Headphones H1, Over Ear Sports Wireless Bluetooth Headphones, Open Ear Headphones Wireless Bluetooth for Runing, Gym Workout, Sports []',
  'parent_asin': 'B0BRMV85ZK'},
 {'preprocessed_content': 'Case for iPad Pro 11 2022/2021/2020/2018 Gen 1st/2nd/3rd/4th,360 Rotatable with Powerful Magnet,2 in 1 Detachable Frosted Clear Case and Semi-Silicone Protective Cover Support Pen Charger(Gray) []',
  'parent_asin': 'B09MD1BK6N'},
 {'preprocessed_content': 'Fintie Case for iPad 10th Generation 10.9 Inch (2022 Model), Multi-Angle Viewing Protective Stand Cover with Pencil Holder & Pocket, Auto Sleep/Wake, Watermelon []',
  'parent_asin': 'B0BK8CQPWD'},
 {'preprocessed_content': 'Wireless Earbud, Bluetooth 5.3 Headphones Sport Wireless Bluetooth Earphones in Ear Noise Cancelling Earbud with Mic Deep Bass, Earhooks Ear Buds IP7 Waterproof 48H Headset for Running Gym[2022 New] []',
  'parent_asin': 'B0C4FBB8LN'},
 {'preprocessed_content': 'Zarler Photo Storage Box 4x6 Picture Boxes, 9 Inner Seed Organizer Cases with Handle, Photo Storage Container Photo Keeper with Provided Sticker Labels (Clear) []',
  'parent_asin': 'B0B2WL2MTC'},
 {'preprocessed_content': 'ZoneFoker for iPad 9th Generation Case, iPad 8th 7th Generation Case, iPad 10.2 Inch 2021/2020/2019 Case, Heavy Duty Rugged Shockproof Protective Cover with Kickstand for Kids (Blue) []',
  'parent_asin': 'B0B1DBFRWL'},
 {'preprocessed_content': 'Troniker Stylish Case for Galaxy Buds 2 Pro (2022)/Galaxy Buds 2 (2021)/Galaxy Buds Pro (2021)/Galaxy Buds Live (2020) for Women Girl Full Protective Hardshell Case (Blue Sky) []',
  'parent_asin': 'B0BRSTFYHT'},
 {'preprocessed_content': "Antkeet Cat7 Ethernet Cable 500ft, 23 AWG Solid Copper, CMR, Double Shielded(S/FTP),1000MHZ / 10 Gigabit Speed Cat 7 LAN Cable 500 ft ['Up to 10Gbps Speed and Multi-shielded Ethernet Cable Antkeet Cat7 network Ethernet cable could transmitting data at high speed up over 300ft run of cable. It is made out of 4 shielded twisted pair (SFTP) of copper wires and GND. Compared to the Cat 6A/6/5 Ethernet cable, the additional shielding and improved quality in twisting of the wires provides better protection from crosstalk, noise, and interference that can degrade the signal quality. Widey use Antkeet Network Ethernet cables offer universal connectivity to computers and network components, such as routers, security cameras, switches, hubs, network printers, game boxes and network attached storage devices , Xbox, PS2,PS3,Ps4 and game boxes. Features 1. Cat 7,SfTP Compatible with Cat5e / Cat6 / Cat6a / Cat6e Ethernet Cable 2. Conductor Construction: 8 wires Solid Copper with shielding and GND, much better than performance than copper clad aluminum (CCA) wire 3. Support bandwidth upto 1000Mhz 4. Support speed up to 10Gbps 5. 23AWG, OD:7 mm 6: Double Shielded(S/FTP) 7. 4PR SFTP copper strands for minimal noise, interference and crosstalk 8. Strange heavy duty cable, flexible PVC jacket 9.Change free and friendly service']",
  'parent_asin': 'B0BZS5MJRP'},
 {'preprocessed_content': "Smart Watch, Fitness Tracker with Heart Rate Monitor, Activity Tracker with Inch Touch Screen,Waterproof,Sleep Monitor,Activity Tracker Pedomet black pro ['2023 latest generation of smart digital watches for men and women', 'Designed for customers looking for appearance, function and exercise, health tracker / message notification / personal assistance / sport mode / waterproof wick / stylish appearance', '➤ Main functions', '● Health tracking: heart rate / blood pressure / sleep monitoring / calories / speed / distance meter / pedometer', '● Notification: call reminder / SMS / email / FB / Twitter / Skype, etc.', '● Personal assistance: alarm clock / stopwatch / sedentary reminder / remote camera', '● Sport mode: walking / running / cycling / soccer', '● Waterproof grade: IP65 degree of protection, easy to use, anti-vibration / ripple. Choose other fun activities or deep water activities.', '➤Specifications', 'Screen: 1.3 inch LCD', 'Bluetooth version: 4.0 (low power consumption)', 'Standby time: 20 days', 'Working time: 4-5 days', 'Charging method: standard USB charging', 'Applicable models: Android 4.4 or above, IOS 8.2 or above', 'Support for Bluetooth version 4.0', 'Language support: English / German / Italian / Spanish / French', '►The package includes:', '2 years maintenance and repair', '1 × smart watch', '1 x exquisite bracelet', '1 x user manual']",
  'parent_asin': 'B0C6F2PSDX'},
 {'preprocessed_content': 'BOZHUORUI Case for 6" Kindle Paperwhite (Fits 10th Generation 2018 and All Paperwhite Generations Prior to 2018) - Premium PU Leather Bookcover with Double Hand Strap (Apricot Flower-1) [\'[Item information]\', \':BOZHUORUI\', \'Case for 6" Kindle Paperwhite (Fits 10th Generation 2018 and All Paperwhite Generations Prior to 2018)\', \'.\', \'[Brand]\', \':BOZHUORUI\', \'[Compatibility]\', \':Compatible with 6" Kindle Paperwhite 5th Generation 2012 Release.Model EY21.Compatible with 6" Kindle Paperwhite 6th Generation 2013 Release,Model EY21.Compatible with 6" Kindle Paperwhite 7th Generation 2015/2017 Release,Model DP75SDI.Compatible with 6" Kindle Paperwhite 10th Generation 2018 Release,Mode PQ94WIF.Please check the model code on the back of the device.\', \'[Will Not Fit]\', \':Not Fit Kindle Touch/Not Fit Kindle Oasis/Not Fit Kindle 10th Generation 2019 Release/Not Fit Kindle 7th Generation 2014 Release/Not Fit Kindle 11th Generation 2022 and Not Fit 6.8 inch Kindle Paperwhite 11th Generation.(Please confirm your device model before purchasing).\', \'[Product Weight]\', \':130 Gram.\', \'[Product Material]\', \':The Surface Layer is Made of High-Quality Faux Leather and Soft Fiber Lining.\', \'[Product Style]\', \':Book Folio Cover\', \'[Product Feature]\', \':with Double Hand Strap\', \'[Product Function]\', \':with Auto Sleep/Wake.\', \'[Magnetic Closure]\', \':Integrated magnets keep the cover securely closed. (The cover can be folded and adsorbed on the back of the protective cover)\', \'[Packaging Information]\', \':Case for 6 inch Kindle Paperwhite * 1\']',
  'parent_asin': 'B094126GYG'},
 {'preprocessed_content': 'TOYOUTHS Compatible with Fitbit Sense/Sense 2 Band/Versa 3/Versa 4 Bands Women Soft Silicone Replacement Strap Dressy Lace Flower Cut-Outs Breathable Waterproof Sport Wristband Accessories []',
  'parent_asin': 'B0B3XWP4PM'},
 {'preprocessed_content': 'Westinghouse 27" Full HD 1080p LED IPS Home Office Computer Monitor, Flicker-Free 75Hz Monitor 27 Inch with IPS Display, Blue Light Filter, and Warm & Cool Mode Viewing, HDMI & VGA Compatible []',
  'parent_asin': 'B0B2D6Z7P9'},
 {'preprocessed_content': 'PIT66 Radio Player Climate Control Bezel W/Speaker Center Dash Panel Lid Finisher Bezel Compatible with 2004-2006 Nissan Titan XE SE Armada SE []',
  'parent_asin': 'B0BPHJ99QH'},
 {'preprocessed_content': '300 Anime Stickers Mixed Pack, Hd Printing Hot Anime Stickers for Water Bottles Laptop Car Computer Skateboard Luggage Hydro Flask, Waterproof Anime Vinyl Stickers for Teens Kids Adults []',
  'parent_asin': 'B0BDTWGY3B'},
 {'preprocessed_content': 'Extra Long iPhone Charger Cord 10 Foot Apple USB A to Lightning Fast Charging Cable 10 Ft 4 Pack for iPhone 14 Pro Max/13/12/11/X/XS/XR/8/7/6/iPad/Air 2/Mini 2/4/iPad 4th gen 10FT []',
  'parent_asin': 'B0BK1MVT44'},
 {'preprocessed_content': 'TEAMGROUP T-Force Delta RGB SSD Lite (Dramless) 512GB with 3D NAND 2.5 Inch SATA III Internal Solid State Drive (R/W Speed up to 550/500 MB/s) Black - T253TR512G3C323 []',
  'parent_asin': 'B08QYL7XPR'},
 {'preprocessed_content': "5 Pack UHF PL259 Solder Connector Plug with Reducer for RG8x, RG8, RG59, LMR-400, RG-213 Coaxial Coax Cable，Teflon Material 50ohm Low Loss RFAdapter Compatiable with Ham Radio Antenna (5-Pack) ['Product Feturess:', 'PL259 Solder Connector Plug+Reducer is perfect for RG59, RG8, RG8x, LMR-400, RG-213 coaxial coax cable.  Suitable for Video Headend Applications.  Adapting reducer included in connector for use with RG-8X Mini-8 RG-59 LMR240.  Nickel-Plated machined brass construction, gold plated contacts and derlin insulator.  High reliability, strong vibration resistance, good mechanical and electrical performance.', 'Product Specifications:', 'Plating: Nickel-plated  Connector Material: Brass  Connector Body Style: Straight  Connector outer conductor: Male  Connector center conductor: Plug  Attachment of cable Center conductor: Soldered  Material: Brass  Net weight: 5pcs: 2.6oz / 75g', 'Package Included:', '5 x PL259 Solder Connector Plug with Reducer.']",
  'parent_asin': 'B09SPQW7VD'},
 {'preprocessed_content': 'Wireless 60% Mechanical Gaming Keyboard, 3 Connection Mode Keyboard with Linear Red Switches, Portabl Compact Grey&Black Keyboard, 68 Keys Mini Keyboard for Mac/Windows, Gamer,Typist,Travel,Trip []',
  'parent_asin': 'B09CTNCBFG'},
 {'preprocessed_content': 'LC-dolida Bluetooth Headband Headphones, Cozy Sleep Mask with Bluetooth Headphones Sleep Headphone Bluetooth Headband with Thin Speaker Handsfree Gadgets Best Gift Ideas (Purple) []',
  'parent_asin': 'B0BLSKG86X'},
 {'preprocessed_content': '2PCS TIK Tok Scroll Remote, TikTok Bluetooth Remote Control Remote Photograph Page Turner, Mini TIK Tok Scrolling Ring for TikTok Bluetooth Remote Control for iPhone,IPad,Android,iOS -Blue and Pink []',
  'parent_asin': 'B0B1MG1QMB'},
 {'preprocessed_content': 'Docking Station for Steam Deck, 6-in-1 Steam Deck Dock with HDMI 2.0 4K@60Hz,1000mbps Gigabit Ethernet, 3 USB-A 3.0 and 100W Charging USB-C Port Compatible with Valve Steam Deck… []',
  'parent_asin': 'B0BTVK6NX1'},
 {'preprocessed_content': 'COOLQO 2 Pack IPX8 Waterproof AirTag Holder Keychain [Mil-Grade Protection] Hard PC Case Cover for Apple Air Tag, Anti-Scratch, Shockproof Tracker for Kids, Luggage, Key, Dog Collar (Clear+Black) []',
  'parent_asin': 'B0BQGDJZV8'},
 {'preprocessed_content': "HENRETY USB C to USB Hub, 4 Port USB 3.0 Adapter USB Splitter,Multi USB Port Expander for iMac Pro, MacBook Air, Mac Mini/Pro, Surface Pro, Notebook PC, Laptop, USB Flash Drives and Mobile HDD(Gray) ['123']",
  'parent_asin': 'B0C2TK8NB4'},
 {'preprocessed_content': 'JJTechGiant Triple Portable Monitor for Laptop Screen Extender Dual Monitor 12 Inch FHD 1080P Tri Screen Display One Type-C Connect Plug and Play No Driver for 13.3-16.5 Inch Laptop Windows 7/8/10/11 []',
  'parent_asin': 'B0BTHTF4GB'},
 {'preprocessed_content': 'Sumgsn 172 Keys Double Shot Apollo Keycaps Cherry Profile for 61/64/87/104/108 Cherry Mx Switches ISO/ANSI Layout Mechanical Keyboard []',
  'parent_asin': 'B09P1GKM24'},
 {'preprocessed_content': 'HIXATEAH 60W Mac Book Pro Charger, Replacement for Mac Book Pro 13-Inch 2012-2015 Retina Display Ac 60W 2 T Connector Power Adapter, Laptop Charger Compatible with Mac Book Pro/Mac Book Air []',
  'parent_asin': 'B0B9N82MXH'},
 {'preprocessed_content': 'Volkano Ninja Kids Earphones for Boys with Carry Case and Keyring - 3.5MM Stereo Jack - Wired Earbuds with Safe Volume 85dB - Earbuds for Kids for School for Online Learning/Travel/Tablet - Red/Blue []',
  'parent_asin': 'B0BBF2VC6X'},
 {'preprocessed_content': 'Aijeff Cleaner Kit for Airpod, Keyboard Cleaner for Laptop, MacBook, Screen Cleaner with Spray and Microfiber Cloth, Multifunctional Cleaning kit for Keyboard, Earphone, Smartphone, Tablet-Blue []',
  'parent_asin': 'B0BYTYMM8Z'},
 {'preprocessed_content': 'Choco Mocha 12.5 Inch Kids Tablet Sleeve Bag []',
  'parent_asin': 'B0BFGHH4QL'},

In [41]:
text_to_embed = [row["preprocessed_content"] for row in data_to_embed]
text_to_embed

["8x8ft Pink Rose Flower Theme Photography Backdrops 3D Pink Floral Newborn Kids Wedding Bridal Shower Photo Background Mother's Day Anniversary Ceremony Couple Photo Props Cake Table Banner ['Details 1. The item color as the picture shown. 2. Made of vinyl cloth. Which is lightweight, thin, easy to carry, durable and wrinkle . 3. May have some creases, but it can be removed. 4. Cannot be washed. 5. Can be folded, easy to place. 6. Non-reflective. 7. The package just have one piece of backdrop. How to remove wrinkles (1)Hang naturally for a few days, no problem. (2) Heat it with a steam iron on the back of item, if necessary, please iron the back surface with steam iron but not dry iron. Then it will be smooth again. Warm-tip Because of the difference between the monitor and the light, here is normal that a slight difference in the color. The picture is clear, realistic, stereo sense is strong. Applications range: It can be used at many situations, such as getting together occasion, weddings,work,graduation,Birthday, Party，home photography any big events or decorations etc. If you have any questions please contact us. We will reply you as soon as possible. Thanks!']",
 'Spigen Tempered Glass Screen Protector [GlasTR EZ FIT] Designed for Galaxy Tab S8 Ultra [9H Hardness/Case-Friendly] []',
 'COLSUR【2023 Newest Bluetooth Speaker with Digital Alarm Clock, Wireless Charger, FM Clock Radio, Adjustable LED Night Light, Dual Wireless Speakers,2500mAh Battery for Bedroom,Home, Adaptor (Wooden) []',
 'Beelink Mini pc 10 Cores 12th Generation Intel i5-1235U(up to 4.4Ghz),TDP 55W 16G DDR4 3200Mhz，500GB M.2 NVMe Pcle 4.0 SSD Mini Desktop Computers, WiFi6, BT5.2, Dual HDMI Business Mini Computers []',
 "ZOVITS U-Shuxian Wireless Earbuds Blutooth 5.3 Headphones for iPhone ['ZOVITS U-Shuxian Wireless Earbuds Lightweight']",
 'SOOPII 100W 6.6ft USB C to USB C Cable Fast Charge, Nylon Braided Type-C Cable with LED Display for lPad Air/lPad Pro, MacBook Pro, Samsung Galaxy S21/S10/S9/Plus (Black) []',
 'Shintop Cord Organizer, 6 Pack Black Charger Holder Cable Clips Wire Clips for Organizing Desk Nightstand Car Phone Charger []',
 'Pad []',
 "ASUS E410 Intel Celeron N4020 4GB 64GB 14-Inch HD LED Win 10 Laptop (Star Black) ['More power, more security, and more ways to do it all. The Asus 14-inch laptop lets you adapt to anything your day has in store, without sacrificing power or security. With the power and versatility you want and a suite of cutting-edge security features you need, you can stay productive and protected like never before. Elevate your entertainment on a high-resolution, micro-edge display.', 'Superb Performance', 'With Intel Celeron N4020 Dual-Core Processor, 4GB RAM, 64GB storage capacity, and Integrated Intel Graphics, you can harness superb productivity power, and keep going with an amazing battery back-up.', 'Stunning Views', 'With a 14-inch HD LED display, all your entertainment and creative projects can shine. Edit photos and stream your media with perfect clarity.', 'Sleek Design', 'Easily take this thin and light PC from room to room or on the road. Take it anywhere and look sharp.', 'Specifications:', 'Intel Celeron N4020 Dual-Core Processor 1.1GHz Up to 2.8GHz', 'Intel Celeron N4020 Dual-Core Processor 1.1GHz Up to 2.8GHz', '4GB SDRAM', '4GB SDRAM', '64GB eMMC Storage', '64GB eMMC Storage', '14-inch HD LED Display (1366 x 768)', '14-inch HD LED Display (1366 x 768)', 'Integrated Intel Graphics', 'Integrated Intel Graphics', 'Webcam', 'Webcam', '2 USB Type-A', '2 USB Type-A', 'HDMI', 'HDMI', 'Card reader', 'Card reader', 'Wi-Fi 802.11', 'Wi-Fi 802.11', '1 headphone/microphone combo', '1 headphone/microphone combo', 'Stereo speakers', 'Stereo speakers', '3-cell Li-ion Battery', '3-cell Li-ion Battery', 'AC power adapter', 'AC power adapter', 'Windows 10', 'Windows 10']",
 "mygreen Electronics Travel Organizer, Electronic Accessories Case with Handle, Portable Tech Travel Gifts for Men Double Layer Cable Storage Bag for Cord, Charger, Ipad Mini Light Green ['Why Mygreen Travel Gadget Organizer Bag?', 'this case is ideal for storing and organizing gadgets of various sizes, such as cellphones, chargers, USB cables, earphones, SD cards, power banks and so on. Mesh pockets and elastic bands allow divisional storage and easy access to all of the electronics and accessories. Double layer design allows holding and securing all your essentials in one place. Mygreen Versatile Organizer is a top solution for small electronics, a must-have for daily life and travel.', 'Storage of Front Layer', '-1 large zipper pocket can fit quick access electronic device.', 'Storage of First Layer', '-1 large pockets with zipper can fit large cell phone like iphone 13/14 pro max etc -1 mesh pocket with zipper can fit portable hard drives, power banks, cameras and cellphones or small items such as USB cables, USB flash disk, MP3 player and other items. -7 elastic straps for organizing various cables, earphones, batteries chargers and more. -7 mesh elastic pockets can fit SD Card, Hard Drive -1 pen slot and 3 leather SD Card holders', 'Storage of Second Layer', '-1 large mesh pocket with with 2 elastic straps for ipad mini -1 mesh zipper pocket for storing cellphones, cards, keys and a little bit of cash. -1 spacious compartment with 4 detachable dividers, which can allow you to design the layouts as your need.', 'Take It Anywhere', '-Perfect for Traveling -This case makes the most efficient use of packing space inside your suitcase or bag.The lightweight handle design allows you to carry the bag anywhere.']",
 'MP3 Player with Bluetooth and WiFi, 4" Full Touch Screen MP4 MP3 Player with Spotify, Android Streaming Music Player with Pandora, Portable HiFi Sound Walkman Digital Audio Player with Speaker (White) []',
 'Jasput USB Splitter Cable,1 Male to 2 Female USB Extension Cable Connectors, Multiport USB Extender Hub,Charger & Data Transfer USB Y Splitter for Laptop,Car,Mac,TV,PC,Xbox One Series X/S,HDD,Phone []',
 'YABER 2022 Upgrade 5G WiFi Bluetooth Projector, 1080P Full HD Supported Portable Projector with Tripod and Carrying Bag, Mini Movie Outdoor Projector Compatible with Smartphone,Laptop,HDMI, VGA,USB,AV []',
 'UGREEN 2 Pack USB Extension Cable, (10 FT+ 10 FT) USB Extender USB 3.0 Extension Cable Nylon Braided Compatible with Webcam, Camera, Phone, USB hub, Mouse, Keyboard, Printer, Hard Drive, Headset []',
 'Military Men Smart Watch(Answer/Make Calls), 2022 Newest Bluetooth Tactical Smart Watch for Android iPhone, IP68 Waterproof Outdoor Tough Rugged Fitness Tracker with AI Voice/Heart Rate/Sleep, Black []',
 'Basesailor USB C to USB C 100W Cable 10FT with USB A Adapter,Fast Charging PD Charger Cord Samsung Galaxy Z Flip Fold 3 4,S9 S10 S10E S23 S20 S21 S22,Note 10 20,A21 A22 A23,A31 A32 A33,A42,A51 A52 A53 []',
 'Aisizon Air Conduction Headphones H1, Over Ear Sports Wireless Bluetooth Headphones, Open Ear Headphones Wireless Bluetooth for Runing, Gym Workout, Sports []',
 'Case for iPad Pro 11 2022/2021/2020/2018 Gen 1st/2nd/3rd/4th,360 Rotatable with Powerful Magnet,2 in 1 Detachable Frosted Clear Case and Semi-Silicone Protective Cover Support Pen Charger(Gray) []',
 'Fintie Case for iPad 10th Generation 10.9 Inch (2022 Model), Multi-Angle Viewing Protective Stand Cover with Pencil Holder & Pocket, Auto Sleep/Wake, Watermelon []',
 'Wireless Earbud, Bluetooth 5.3 Headphones Sport Wireless Bluetooth Earphones in Ear Noise Cancelling Earbud with Mic Deep Bass, Earhooks Ear Buds IP7 Waterproof 48H Headset for Running Gym[2022 New] []',
 'Zarler Photo Storage Box 4x6 Picture Boxes, 9 Inner Seed Organizer Cases with Handle, Photo Storage Container Photo Keeper with Provided Sticker Labels (Clear) []',
 'ZoneFoker for iPad 9th Generation Case, iPad 8th 7th Generation Case, iPad 10.2 Inch 2021/2020/2019 Case, Heavy Duty Rugged Shockproof Protective Cover with Kickstand for Kids (Blue) []',
 'Troniker Stylish Case for Galaxy Buds 2 Pro (2022)/Galaxy Buds 2 (2021)/Galaxy Buds Pro (2021)/Galaxy Buds Live (2020) for Women Girl Full Protective Hardshell Case (Blue Sky) []',
 "Antkeet Cat7 Ethernet Cable 500ft, 23 AWG Solid Copper, CMR, Double Shielded(S/FTP),1000MHZ / 10 Gigabit Speed Cat 7 LAN Cable 500 ft ['Up to 10Gbps Speed and Multi-shielded Ethernet Cable Antkeet Cat7 network Ethernet cable could transmitting data at high speed up over 300ft run of cable. It is made out of 4 shielded twisted pair (SFTP) of copper wires and GND. Compared to the Cat 6A/6/5 Ethernet cable, the additional shielding and improved quality in twisting of the wires provides better protection from crosstalk, noise, and interference that can degrade the signal quality. Widey use Antkeet Network Ethernet cables offer universal connectivity to computers and network components, such as routers, security cameras, switches, hubs, network printers, game boxes and network attached storage devices , Xbox, PS2,PS3,Ps4 and game boxes. Features 1. Cat 7,SfTP Compatible with Cat5e / Cat6 / Cat6a / Cat6e Ethernet Cable 2. Conductor Construction: 8 wires Solid Copper with shielding and GND, much better than performance than copper clad aluminum (CCA) wire 3. Support bandwidth upto 1000Mhz 4. Support speed up to 10Gbps 5. 23AWG, OD:7 mm 6: Double Shielded(S/FTP) 7. 4PR SFTP copper strands for minimal noise, interference and crosstalk 8. Strange heavy duty cable, flexible PVC jacket 9.Change free and friendly service']",
 "Smart Watch, Fitness Tracker with Heart Rate Monitor, Activity Tracker with Inch Touch Screen,Waterproof,Sleep Monitor,Activity Tracker Pedomet black pro ['2023 latest generation of smart digital watches for men and women', 'Designed for customers looking for appearance, function and exercise, health tracker / message notification / personal assistance / sport mode / waterproof wick / stylish appearance', '➤ Main functions', '● Health tracking: heart rate / blood pressure / sleep monitoring / calories / speed / distance meter / pedometer', '● Notification: call reminder / SMS / email / FB / Twitter / Skype, etc.', '● Personal assistance: alarm clock / stopwatch / sedentary reminder / remote camera', '● Sport mode: walking / running / cycling / soccer', '● Waterproof grade: IP65 degree of protection, easy to use, anti-vibration / ripple. Choose other fun activities or deep water activities.', '➤Specifications', 'Screen: 1.3 inch LCD', 'Bluetooth version: 4.0 (low power consumption)', 'Standby time: 20 days', 'Working time: 4-5 days', 'Charging method: standard USB charging', 'Applicable models: Android 4.4 or above, IOS 8.2 or above', 'Support for Bluetooth version 4.0', 'Language support: English / German / Italian / Spanish / French', '►The package includes:', '2 years maintenance and repair', '1 × smart watch', '1 x exquisite bracelet', '1 x user manual']",
 'BOZHUORUI Case for 6" Kindle Paperwhite (Fits 10th Generation 2018 and All Paperwhite Generations Prior to 2018) - Premium PU Leather Bookcover with Double Hand Strap (Apricot Flower-1) [\'[Item information]\', \':BOZHUORUI\', \'Case for 6" Kindle Paperwhite (Fits 10th Generation 2018 and All Paperwhite Generations Prior to 2018)\', \'.\', \'[Brand]\', \':BOZHUORUI\', \'[Compatibility]\', \':Compatible with 6" Kindle Paperwhite 5th Generation 2012 Release.Model EY21.Compatible with 6" Kindle Paperwhite 6th Generation 2013 Release,Model EY21.Compatible with 6" Kindle Paperwhite 7th Generation 2015/2017 Release,Model DP75SDI.Compatible with 6" Kindle Paperwhite 10th Generation 2018 Release,Mode PQ94WIF.Please check the model code on the back of the device.\', \'[Will Not Fit]\', \':Not Fit Kindle Touch/Not Fit Kindle Oasis/Not Fit Kindle 10th Generation 2019 Release/Not Fit Kindle 7th Generation 2014 Release/Not Fit Kindle 11th Generation 2022 and Not Fit 6.8 inch Kindle Paperwhite 11th Generation.(Please confirm your device model before purchasing).\', \'[Product Weight]\', \':130 Gram.\', \'[Product Material]\', \':The Surface Layer is Made of High-Quality Faux Leather and Soft Fiber Lining.\', \'[Product Style]\', \':Book Folio Cover\', \'[Product Feature]\', \':with Double Hand Strap\', \'[Product Function]\', \':with Auto Sleep/Wake.\', \'[Magnetic Closure]\', \':Integrated magnets keep the cover securely closed. (The cover can be folded and adsorbed on the back of the protective cover)\', \'[Packaging Information]\', \':Case for 6 inch Kindle Paperwhite * 1\']',
 'TOYOUTHS Compatible with Fitbit Sense/Sense 2 Band/Versa 3/Versa 4 Bands Women Soft Silicone Replacement Strap Dressy Lace Flower Cut-Outs Breathable Waterproof Sport Wristband Accessories []',
 'Westinghouse 27" Full HD 1080p LED IPS Home Office Computer Monitor, Flicker-Free 75Hz Monitor 27 Inch with IPS Display, Blue Light Filter, and Warm & Cool Mode Viewing, HDMI & VGA Compatible []',
 'PIT66 Radio Player Climate Control Bezel W/Speaker Center Dash Panel Lid Finisher Bezel Compatible with 2004-2006 Nissan Titan XE SE Armada SE []',
 '300 Anime Stickers Mixed Pack, Hd Printing Hot Anime Stickers for Water Bottles Laptop Car Computer Skateboard Luggage Hydro Flask, Waterproof Anime Vinyl Stickers for Teens Kids Adults []',
 'Extra Long iPhone Charger Cord 10 Foot Apple USB A to Lightning Fast Charging Cable 10 Ft 4 Pack for iPhone 14 Pro Max/13/12/11/X/XS/XR/8/7/6/iPad/Air 2/Mini 2/4/iPad 4th gen 10FT []',
 'TEAMGROUP T-Force Delta RGB SSD Lite (Dramless) 512GB with 3D NAND 2.5 Inch SATA III Internal Solid State Drive (R/W Speed up to 550/500 MB/s) Black - T253TR512G3C323 []',
 "5 Pack UHF PL259 Solder Connector Plug with Reducer for RG8x, RG8, RG59, LMR-400, RG-213 Coaxial Coax Cable，Teflon Material 50ohm Low Loss RFAdapter Compatiable with Ham Radio Antenna (5-Pack) ['Product Feturess:', 'PL259 Solder Connector Plug+Reducer is perfect for RG59, RG8, RG8x, LMR-400, RG-213 coaxial coax cable.  Suitable for Video Headend Applications.  Adapting reducer included in connector for use with RG-8X Mini-8 RG-59 LMR240.  Nickel-Plated machined brass construction, gold plated contacts and derlin insulator.  High reliability, strong vibration resistance, good mechanical and electrical performance.', 'Product Specifications:', 'Plating: Nickel-plated  Connector Material: Brass  Connector Body Style: Straight  Connector outer conductor: Male  Connector center conductor: Plug  Attachment of cable Center conductor: Soldered  Material: Brass  Net weight: 5pcs: 2.6oz / 75g', 'Package Included:', '5 x PL259 Solder Connector Plug with Reducer.']",
 'Wireless 60% Mechanical Gaming Keyboard, 3 Connection Mode Keyboard with Linear Red Switches, Portabl Compact Grey&Black Keyboard, 68 Keys Mini Keyboard for Mac/Windows, Gamer,Typist,Travel,Trip []',
 'LC-dolida Bluetooth Headband Headphones, Cozy Sleep Mask with Bluetooth Headphones Sleep Headphone Bluetooth Headband with Thin Speaker Handsfree Gadgets Best Gift Ideas (Purple) []',
 '2PCS TIK Tok Scroll Remote, TikTok Bluetooth Remote Control Remote Photograph Page Turner, Mini TIK Tok Scrolling Ring for TikTok Bluetooth Remote Control for iPhone,IPad,Android,iOS -Blue and Pink []',
 'Docking Station for Steam Deck, 6-in-1 Steam Deck Dock with HDMI 2.0 4K@60Hz,1000mbps Gigabit Ethernet, 3 USB-A 3.0 and 100W Charging USB-C Port Compatible with Valve Steam Deck… []',
 'COOLQO 2 Pack IPX8 Waterproof AirTag Holder Keychain [Mil-Grade Protection] Hard PC Case Cover for Apple Air Tag, Anti-Scratch, Shockproof Tracker for Kids, Luggage, Key, Dog Collar (Clear+Black) []',
 "HENRETY USB C to USB Hub, 4 Port USB 3.0 Adapter USB Splitter,Multi USB Port Expander for iMac Pro, MacBook Air, Mac Mini/Pro, Surface Pro, Notebook PC, Laptop, USB Flash Drives and Mobile HDD(Gray) ['123']",
 'JJTechGiant Triple Portable Monitor for Laptop Screen Extender Dual Monitor 12 Inch FHD 1080P Tri Screen Display One Type-C Connect Plug and Play No Driver for 13.3-16.5 Inch Laptop Windows 7/8/10/11 []',
 'Sumgsn 172 Keys Double Shot Apollo Keycaps Cherry Profile for 61/64/87/104/108 Cherry Mx Switches ISO/ANSI Layout Mechanical Keyboard []',
 'HIXATEAH 60W Mac Book Pro Charger, Replacement for Mac Book Pro 13-Inch 2012-2015 Retina Display Ac 60W 2 T Connector Power Adapter, Laptop Charger Compatible with Mac Book Pro/Mac Book Air []',
 'Volkano Ninja Kids Earphones for Boys with Carry Case and Keyring - 3.5MM Stereo Jack - Wired Earbuds with Safe Volume 85dB - Earbuds for Kids for School for Online Learning/Travel/Tablet - Red/Blue []',
 'Aijeff Cleaner Kit for Airpod, Keyboard Cleaner for Laptop, MacBook, Screen Cleaner with Spray and Microfiber Cloth, Multifunctional Cleaning kit for Keyboard, Earphone, Smartphone, Tablet-Blue []',
 'Choco Mocha 12.5 Inch Kids Tablet Sleeve Bag []',
 "Garmin Forerunner® 955 Solar, GPS Running Smartwatch with Solar Charging Capabilities, Tailored to Triathletes, Long-Lasting Battery, Whitestone ['Lead the pack with Forerunner® 955 Solar, the premium GPS running and triathlon smartwatch with Power Glass™ solar charging to extend battery life. The training readiness feature tells you when you’re primed for a productive session — while daily suggested workouts adapt to your performance and recovery alongside the race widget, which provides training tips, course details and completion time predictions. With morning report, you can get an overview of your sleep, recovery, training and more — as well as a picture of your overall health with heart rate variability (HRV) status (This device is intended to give an estimate of your activity and metrics). On the run, new multi-band GPS and full-color, built-in maps help you navigate confidently. And with traditional buttons and a touch display, it has never been easier to tap into your training status and know whether you’re training productively, peaking or strained. If you’re pushing toward the podium — or to the very limits — Forerunner 955 Solar is by your side with up to 20 days of battery life with solar charging in smartwatch mode (assuming all-day wear with 3 hours per day outside in 50,000 lux conditions).']",
 'YIWENTEC USB4 8K 0.5M Cable Thunderbolt 4 USB 4 Type-c Male Angle to Female Extension Cable Ultra HD 8K@60Hz 100W Charging 40Gbps Data Transfer Compatible with External SSD eGPU USB-C Docking [\'USB4.0 Type-c M/F Cable,Outer Diameter5.0mm,Connector Gold plated,Guaranteed transmission rate,Pure Cooper cable with braided Nylon.USB-C Connector.\', \'USB4 compatible with Thunderbolt 4 and Thunderbolt 3 ,Use function introduction:\', \'1 Video Output:It allows to connect from your USB-C Devices to your Monitors with USB C Port,it can max support Ultra HD 8K@60Hz 5K@60Hz,4K@120Hz Video Resolution.An additional USB 4 Male to Male cable is needed,but not included in our Package. 2 40Gbps Data Transfer:You can connect with your Hard Driver Devices or other data storage device for data transfer,transfer rate can reach max to 40Gbps(USB3.1 is 10Gbps,?TB2 is 20Gbps). 3 20V 5A Power Delivery:You can connect from power adapter to your USB-C Devices and charge your Laptops or other Type-c Devices.Supporting Max 20V/5A 100W Charging.\', \'Important Notes While Using:\', "1:If you would like to output video via this USB 4 Type-c Cable,your source devices and your monitors\' relatively port should all support dp alternate mode for video transmitting. 2:The transfer rate ultimately depends on your device and your own data.", \'What you will get:\', \'1x0.8m USB4 M/F Cable\']',
 'New 2023 80x100 HD Monoculars for Adults high Powered,Fyzpaea BAK-4 Prism and FMC Lens Monocular Telescope for Smartphone,Low Night Vision Monoculars for Bird Watching/Wildlife/Hunting/Hiking []',

In [ ]:
#### Performing Embedding ####
embeddings = get_embeddings_batch(text_to_embed, batch_size=200)

Batch #1: 200 / 1000
Batch #2: 400 / 1000
Batch #3: 600 / 1000
Batch #4: 800 / 1000
Batch #5: 1000 / 1000

In [43]:
pointstructs = []
counter = 1

for embedding, data in zip(embeddings, data_to_embed):
    pointstructs.append(
        PointStruct(
            id=counter,
            vector={
                "text-embedding-3-small": embedding
            },
            payload=data
        )
    )
    counter += 1

In [44]:
pointstructs[0].vector

{'text-embedding-3-small': [0.03125,
  0.027130126953125,
  -0.01345062255859375,
  -0.012481689453125,
  -0.03729248046875,
  -0.0423583984375,
  0.014495849609375,
  -0.0188751220703125,
  -0.01528167724609375,
  0.021575927734375,
  -0.0130157470703125,
  0.033782958984375,
  -0.01280975341796875,
  -0.031280517578125,
  -0.0234222412109375,
  0.046051025390625,
  0.032684326171875,
  0.047943115234375,
  -0.0002968311309814453,
  0.01134490966796875,
  0.038055419921875,
  -0.005641937255859375,
  -0.025421142578125,
  -0.0350341796875,
  0.036590576171875,
  0.01433563232421875,
  0.07196044921875,
  -0.0330810546875,
  0.02685546875,
  -0.0003001689910888672,
  -0.034576416015625,
  -0.035491943359375,
  0.037139892578125,
  -0.07183837890625,
  0.0202178955078125,
  0.0023193359375,
  -0.0233154296875,
  -0.01317596435546875,
  -0.0194244384765625,
  0.01073455810546875,
  0.053436279296875,
  0.017974853515625,
  0.0208740234375,
  -0.045562744140625,
  -0.02239990234375,
  0.052154541015625,
  -0.031646728515625,
  0.036376953125,
  -0.0184783935546875,
  0.00482940673828125,
  -0.002887725830078125,
  0.06915283203125,
  -0.018524169921875,
  -0.021881103515625,
  -0.0033626556396484375,
  -0.0134429931640625,
  0.0251007080078125,
  -0.0023250579833984375,
  0.00791168212890625,
  0.009368896484375,
  0.043701171875,
  -0.051605224609375,
  0.0169525146484375,
  0.031646728515625,
  0.01422119140625,
  0.005878448486328125,
  -0.0682373046875,
  0.022186279296875,
  0.001811981201171875,
  -0.036163330078125,
  0.0272064208984375,
  0.0089569091796875,
  -0.01605224609375,
  0.0007252693176269531,
  -0.023651123046875,
  0.03106689453125,
  0.016326904296875,
  -0.037445068359375,
  0.012420654296875,
  0.00658416748046875,
  0.0114593505859375,
  -0.0133514404296875,
  -0.060272216796875,
  0.047821044921875,
  0.0010700225830078125,
  -0.004547119140625,
  -0.0428466796875,
  0.0179290771484375,
  -0.01331329345703125,
  0.0303192138671875,
  -0.0316162109375,
  0.007282257080078125,
  0.003414154052734375,
  0.01214599609375,
  0.047943115234375,
  -0.00019466876983642578,
  -0.0294647216796875,
  -0.0240478515625,
  -0.00969696044921875,
  0.03436279296875,
  0.00937652587890625,
  -0.004413604736328125,
  -0.019622802734375,
  -0.0165863037109375,
  0.004299163818359375,
  -0.03387451171875,
  0.00910186767578125,
  -0.032440185546875,
  -0.0208892822265625,
  0.038360595703125,
  -0.07659912109375,
  -0.0048370361328125,
  0.00498199462890625,
  0.04620361328125,
  -0.002056121826171875,
  0.0301361083984375,
  0.0233001708984375,
  0.005329132080078125,
  -0.018524169921875,
  -0.0322265625,
  -0.0100250244140625,
  0.025299072265625,
  0.0012359619140625,
  -0.0015058517456054688,
  -0.00782012939453125,
  -0.01300811767578125,
  0.02239990234375,
  -0.00571441650390625,
  -0.00977325439453125,
  -0.0021762847900390625,
  0.02630615234375,
  0.002841949462890625,
  0.03350830078125,
  0.0008907318115234375,
  -8.147954940795898e-05,
  0.007503509521484375,
  0.042205810546875,
  0.0114593505859375,
  -0.0206451416015625,
  0.005031585693359375,
  0.056549072265625,
  -0.06695556640625,
  -0.01184844970703125,
  -0.0013790130615234375,
  0.03277587890625,
  0.08062744140625,
  0.01427459716796875,
  0.03631591796875,
  0.0118255615234375,
  0.06402587890625,
  -0.0304107666015625,
  -0.018798828125,
  0.004364013671875,
  0.0102691650390625,
  -0.0206451416015625,
  -0.053955078125,
  0.050201416015625,
  0.0110931396484375,
  -0.034759521484375,
  0.01139068603515625,
  -0.046173095703125,
  0.006908416748046875,
  -0.004962921142578125,
  -0.005786895751953125,
  -0.0148162841796875,
  -0.0408935546875,
  -0.007659912109375,
  0.0269927978515625,
  -0.0237884521484375,
  -0.0350341796875,
  0.00899505615234375,
  -0.0080108642578125,
  0.009490966796875,
  0.019439697265625,
  -0.03765869140625,
  0.0377197265625,
  0.08111572265625,
  -0.0171966552734375,
  0.041290283203125,
  0.00827789306640625,
  0.05780029296875,
  0.054229736328125,
  0.017578125,
  -0.06512451171875,
  -0.004962921142578125,
  -0.0185699462890625,
  0.0086212158203125,
  -0.0310516357421875,
  -0.033447265625,
  0.01580810546875,
  -0.006023406982421875,
  0.007045745849609375,
  0.0037555694580078125,
  0.01020050048828125,
  0.0258026123046875,
  -0.050201416015625,
  0.044097900390625,
  -0.00859832763671875,
  -0.03289794921875,
  0.00787353515625,
  -0.00511932373046875,
  -0.01181793212890625,
  0.0009002685546875,
  -0.0005159378051757812,
  -0.01214599609375,
  -0.0277252197265625,
  -0.05230712890625,
  -0.00669097900390625,
  0.008392333984375,
  0.0162353515625,
  0.0653076171875,
  -0.03173828125,
  -0.038818359375,
  -0.0186614990234375,
  -0.00585174560546875,
  -0.00977325439453125,
  -0.0023345947265625,
  -0.0124359130859375,
  -0.018341064453125,
  0.03485107421875,
  -0.03704833984375,
  0.006927490234375,
  0.03118896484375,
  -0.00376129150390625,
  0.02386474609375,
  -0.0242919921875,
  0.01849365234375,
  -0.0401611328125,
  -0.0277557373046875,
  -0.0245208740234375,
  -0.0192718505859375,
  0.046600341796875,
  -0.023681640625,
  0.025787353515625,
  0.042633056640625,
  -0.0201416015625,
  -0.09002685546875,
  -0.010772705078125,
  -0.0224761962890625,
  -0.006175994873046875,
  0.006175994873046875,
  -0.0009775161743164062,
  -0.058624267578125,
  -0.0151824951171875,
  -0.00682830810546875,
  0.01363372802734375,
  -0.00833892822265625,
  -0.0290985107421875,
  0.0300445556640625,
  0.0008587837219238281,
  0.053802490234375,
  -0.0278167724609375,
  -0.019012451171875,
  -0.028717041015625,
  0.0460205078125,
  -0.003871917724609375,
  0.018707275390625,
  0.0170135498046875,
  -0.00316619873046875,
  -0.029144287109375,
  0.0158233642578125,
  -0.034759521484375,
  -0.056915283203125,
  0.00957489013671875,
  0.08233642578125,
  0.029876708984375,
  0.0092620849609375,
  0.0572509765625,
  0.014801025390625,
  0.01422119140625,
  0.0226898193359375,
  -0.0350341796875,
  0.0467529296875,
  0.0511474609375,
  -0.004016876220703125,
  0.0148162841796875,
  -0.0005488395690917969,
  -0.053131103515625,
  0.032867431640625,
  0.00173187255859375,
  0.01377105712890625,
  -0.004154205322265625,
  -0.019622802734375,
  -0.030975341796875,
  -0.001995086669921875,
  0.026947021484375,
  0.0167236328125,
  0.0223236083984375,
  -0.0203094482421875,
  0.0160064697265625,
  -0.01617431640625,
  -0.02789306640625,
  0.005512237548828125,
  -0.0076751708984375,
  -0.0012674331665039062,
  -0.032806396484375,
  -0.0109405517578125,
  0.07110595703125,
  -0.04547119140625,
  -0.038604736328125,
  -0.01351165771484375,
  -0.060028076171875,
  0.02423095703125,
  0.004314422607421875,
  -0.040496826171875,
  0.00942230224609375,
  -0.0160980224609375,
  0.00850677490234375,
  0.0259246826171875,
  0.0218963623046875,
  -0.00556182861328125,
  0.015960693359375,
  -0.0254669189453125,
  -0.083984375,
  -0.045440673828125,
  0.052154541015625,
  -0.020751953125,
  0.0272064208984375,
  0.0052642822265625,
  -0.04010009765625,
  0.052886962890625,
  0.00919342041015625,
  0.0088043212890625,
  0.0015859603881835938,
  -0.0159149169921875,
  -0.0499267578125,
  0.0018949508666992188,
  -0.0294647216796875,
  0.046600341796875,
  0.0264434814453125,
  -0.053131103515625,
  -0.0198516845703125,
  0.001949310302734375,
  -0.038055419921875,
  0.01079559326171875,
  0.00909423828125,
  0.01751708984375,
  -0.013214111328125,
  -0.017333984375,
  -0.058807373046875,
  -0.03302001953125,
  -0.08734130859375,
  -0.0101470947265625,
  -0.0175018310546875,
  -0.061920166015625,
  -0.01299285888671875,
  0.0313720703125,
  -0.0007104873657226562,
  0.0243377685546875,
  0.0213165283203125,
  -0.0300140380859375,
  0.032684326171875,
  0.028778076171875,
  0.0124359130859375,
  0.07940673828125,
  -0.027618408203125,
  0.040374755859375,
  0.023040771484375,
  -0.0247039794921875,
  0.042022705078125,
  0.008056640625,
  0.022186279296875,
  0.003314971923828125,
  -0.0287628173828125,
  -0.0250701904296875,
  -0.00417327880859375,
  -0.01413726806640625,
  0.038848876953125,
  0.00510406494140625,
  -0.003509521484375,
  0.01152801513671875,
  0.040679931640625,
  0.0173797607421875,
  0.0202789306640625,
  -0.04345703125,
  -0.05963134765625,
  0.027984619140625,
  0.014678955078125,
  0.00244903564453125,
  -0.0204925537109375,
  -0.019775390625,
  -0.045318603515625,
  0.0209808349609375,
  0.0406494140625,
  0.0259857177734375,
  -0.0204315185546875,
  -0.044219970703125,
  0.004566192626953125,
  -0.0009093284606933594,
  -0.0019321441650390625,
  0.0220489501953125,
  -0.01465606689453125,
  0.0394287109375,
  0.0231475830078125,
  0.05157470703125,
  0.033538818359375,
  -0.01143646240234375,
  0.040771484375,
  -0.017425537109375,
  0.009307861328125,
  -0.0197601318359375,
  -0.055419921875,
  -0.0467529296875,
  0.032379150390625,
  -0.005710601806640625,
  -0.0235595703125,
  0.011505126953125,
  -0.023284912109375,
  0.02899169921875,
  0.00551605224609375,
  -0.04510498046875,
  -0.033935546875,
  0.0269927978515625,
  0.052581787109375,
  -0.023193359375,
  0.0105133056640625,
  0.0491943359375,
  0.004497528076171875,
  -0.010589599609375,
  -0.00923919677734375,
  -0.0015211105346679688,
  0.033935546875,
  -0.01222991943359375,
  -0.032867431640625,
  -0.07403564453125,
  0.0220184326171875,
  -0.00719451904296875,
  -0.0307769775390625,
  -0.0762939453125,
  -0.045928955078125,
  -0.0225677490234375,
  -0.017364501953125,
  0.0271759033203125,
  -0.036041259765625,
  -0.01033782958984375,
  0.00963592529296875,
  -0.0022525787353515625,
  0.01560211181640625,
  0.003543853759765625,
  0.00443267822265625,
  0.009613037109375,
  -0.0068817138671875,
  -0.0025177001953125,
  0.01465606689453125,
  -0.0194854736328125,
  0.060455322265625,
  -0.0248870849609375,
  0.057464599609375,
  -0.049041748046875,
  -0.048858642578125,
  -0.01543426513671875,
  0.00733184814453125,
  0.00426483154296875,
  0.02410888671875,
  0.0176544189453125,
  0.0242919921875,
  0.0158843994140625,
  -0.028350830078125,
  0.01470947265625,
  -0.043609619140625,
  -0.00997161865234375,
  0.0169830322265625,
  0.036773681640625,
  0.0643310546875,
  -0.015899658203125,
  0.0294647216796875,
  -0.050567626953125,
  -0.0161895751953125,
  -0.004917144775390625,
  -0.067626953125,
  -0.0162353515625,
  0.00804901123046875,
  0.032440185546875,
  -0.07220458984375,
  0.015777587890625,
  -0.0019464492797851562,
  0.02703857421875,
  -0.0004661083221435547,
  -0.023773193359375,
  -0.032196044921875,
  0.01349639892578125,
  0.0335693359375,
  -0.038604736328125,
  -0.015960693359375,
  -0.005443572998046875,
  0.041412353515625,
  0.0150909423828125,
  -0.044677734375,
  -0.0224151611328125,
  0.036865234375,
  -0.0350341796875,
  0.0312042236328125,
  0.01271820068359375,
  -0.00955963134765625,
  0.02960205078125,
  -0.07012939453125,
  0.0150299072265625,
  0.01409149169921875,
  -0.05517578125,
  0.013153076171875,
  -0.0026607513427734375,
  -0.015045166015625,
  0.01511383056640625,
  -0.04595947265625,
  0.08306884765625,
  0.00337982177734375,
  0.0213165283203125,
  -0.004398345947265625,
  0.0164642333984375,
  -0.0018033981323242188,
  -0.032196044921875,
  -0.005260467529296875,
  0.0258941650390625,
  0.0251617431640625,
  -0.007808685302734375,
  -0.01551055908203125,
  0.0024509429931640625,
  0.00827789306640625,
  -0.040985107421875,
  0.01383209228515625,
  0.0053253173828125,
  0.0190277099609375,
  0.0159912109375,
  -0.01450347900390625,
  -0.011138916015625,
  -0.060577392578125,
  -0.0294647216796875,
  -0.047637939453125,
  0.0126953125,
  -0.019683837890625,
  -0.006381988525390625,
  -0.0139923095703125,
  -0.053497314453125,
  0.031494140625,
  -0.019287109375,
  0.004329681396484375,
  0.0169677734375,
  0.00804901123046875,
  -0.002918243408203125,
  0.006961822509765625,
  -0.00563812255859375,
  0.0009899139404296875,
  0.0095672607421875,
  -0.00919342041015625,
  -0.0019102096557617188,
  0.03338623046875,
  0.01172637939453125,
  0.0190277099609375,
  -0.0015716552734375,
  0.0004703998565673828,
  0.0182647705078125,
  -0.004055023193359375,
  -0.01113128662109375,
  -0.03082275390625,
  -0.00260162353515625,
  0.01568603515625,
  -0.004276275634765625,
  0.00870513916015625,
  0.0190277099609375,
  0.040496826171875,
  0.062286376953125,
  -0.01123046875,
  0.0029430389404296875,
  0.0254669189453125,
  0.034210205078125,
  0.04571533203125,
  0.0177001953125,
  -0.0025310516357421875,
  -0.011962890625,
  -0.03680419921875,
  -0.054718017578125,
  0.0066986083984375,
  0.0006656646728515625,
  -0.024139404296875,
  -0.00948333740234375,
  0.0090789794921875,
  0.02850341796875,
  -0.01296234130859375,
  -0.0156402587890625,
  -0.03594970703125,
  -0.028594970703125,
  -0.03741455078125,
  -0.0161285400390625,
  -0.033477783203125,
  -0.0401611328125,
  0.01015472412109375,
  -0.0019779205322265625,
  -0.021636962890625,
  0.019195556640625,
  0.01305389404296875,
  -0.01239013671875,
  -0.007686614990234375,
  -0.0014638900756835938,
  0.00878143310546875,
  0.032928466796875,
  0.01541900634765625,
  -0.044219970703125,
  0.022552490234375,
  -0.00252532958984375,
  -0.0305938720703125,
  0.0079345703125,
  -0.016632080078125,
  -0.0284423828125,
  0.007843017578125,
  0.020965576171875,
  0.0193328857421875,
  0.002227783203125,
  -0.0430908203125,
  -0.0188751220703125,
  -0.003849029541015625,
  0.026580810546875,
  0.02191162109375,
  0.012054443359375,
  0.023590087890625,
  0.0012578964233398438,
  0.0131072998046875,
  -0.0004780292510986328,
  0.0288238525390625,
  -0.007091522216796875,
  -0.02740478515625,
  -0.0159149169921875,
  4.3272972106933594e-05,
  0.01751708984375,
  -0.01995849609375,
  0.02569580078125,
  0.035797119140625,
  -0.018341064453125,
  -0.0013380050659179688,
  -0.0167388916015625,
  0.017486572265625,
  0.004123687744140625,
  -0.0341796875,
  0.009002685546875,
  -0.02423095703125,
  0.00933074951171875,
  -0.0057830810546875,
  0.012237548828125,
  -0.007511138916015625,
  -0.0258026123046875,
  -0.0098114013671875,
  0.04840087890625,
  0.0295867919921875,
  0.01277923583984375,
  -0.044189453125,
  -0.0081024169921875,
  0.0019092559814453125,
  -0.01093292236328125,
  0.01568603515625,
  -0.0249786376953125,
  0.0031719207763671875,
  0.01042938232421875,
  0.0021343231201171875,
  0.0074310302734375,
  0.0034637451171875,
  -0.0004181861877441406,
  0.01385498046875,
  -0.009307861328125,
  0.0240936279296875,
  -0.016510009765625,
  0.0350341796875,
  -0.0270233154296875,
  0.05633544921875,
  -0.01038360595703125,
  -0.036529541015625,
  0.023681640625,
  -0.002227783203125,
  0.0014514923095703125,
  -0.00047969818115234375,
  0.0030117034912109375,
  -0.025482177734375,
  0.042999267578125,
  0.021820068359375,
  -0.003322601318359375,
  -0.005584716796875,
  -0.024322509765625,
  0.0027599334716796875,
  -0.021514892578125,
  -0.02099609375,
  0.00954437255859375,
  0.04150390625,
  -0.00891876220703125,
  0.00435638427734375,
  -0.0212249755859375,
  -0.0001704692840576172,
  0.01200103759765625,
  -0.01081085205078125,
  -0.027496337890625,
  0.0030975341796875,
  0.0119781494140625,
  -0.0306549072265625,
  -0.01507568359375,
  0.0204620361328125,
  -0.00881195068359375,
  0.02734375,
  0.01450347900390625,
  0.0105438232421875,
  -0.033935546875,
  -0.01328277587890625,
  0.00453948974609375,
  -0.022552490234375,
  0.02569580078125,
  0.0141754150390625,
  -0.01116180419921875,
  -0.04949951171875,
  -0.0262451171875,
  0.023773193359375,
  -0.00991058349609375,
  0.0256500244140625,
  0.01399993896484375,
  0.00858306884765625,
  -0.006744384765625,
  0.017730712890625,
  -0.01212310791015625,
  -0.0186004638671875,
  -0.018157958984375,
  -0.026885986328125,
  0.00814056396484375,
  0.00632476806640625,
  -0.0086212158203125,
  0.0058441162109375,
  -0.00438690185546875,
  0.0013208389282226562,
  -0.00223541259765625,
  0.007537841796875,
  0.024139404296875,
  -0.005336761474609375,
  0.0098724365234375,
  -0.0199127197265625,
  -0.0170440673828125,
  0.022369384765625,
  0.01059722900390625,
  -0.01222991943359375,
  0.0126190185546875,
  0.054412841796875,
  0.033294677734375,
  0.0089874267578125,
  -0.03411865234375,
  0.03033447265625,
  -0.016143798828125,
  -0.04718017578125,
  0.0182342529296875,
  -0.033660888671875,
  -0.024932861328125,
  0.02301025390625,
  -0.0249786376953125,
  0.0290985107421875,
  0.04107666015625,
  0.01345062255859375,
  -0.01605224609375,
  -0.0261688232421875,
  -0.006496429443359375,
  0.007022857666015625,
  0.006206512451171875,
  -0.0188140869140625,
  -0.0025653839111328125,
  0.035003662109375,
  -0.01348876953125,
  -0.0257110595703125,
  -0.0234222412109375,
  0.016693115234375,
  0.01507568359375,
  0.0183868408203125,
  -0.003459930419921875,
  0.02899169921875,
  -1.5020370483398438e-05,
  0.0202178955078125,
  -0.03314208984375,
  0.0482177734375,
  -0.031982421875,
  -0.00121307373046875,
  -0.009552001953125,
  0.0128936767578125,
  0.01345062255859375,
  -0.00533294677734375,
  -0.015533447265625,
  0.029052734375,
  -0.009521484375,
  -0.0158538818359375,
  -0.01047515869140625,
  0.009307861328125,
  0.01134490966796875,
  0.0179443359375,
  0.0307769775390625,
  0.02215576171875,
  0.0263519287109375,
  -0.0372314453125,
  -0.004802703857421875,
  -0.0004968643188476562,
  -0.05120849609375,
  -0.0312347412109375,
  -0.022705078125,
  -0.040618896484375,
  0.0222930908203125,
  -0.018341064453125,
  -0.0421142578125,
  0.05078125,
  0.0113525390625,
  -0.003070831298828125,
  0.042144775390625,
  0.024688720703125,
  -0.04803466796875,
  0.0240020751953125,
  -0.029541015625,
  -0.0248870849609375,
  0.01328277587890625,
  0.0150909423828125,
  0.01245880126953125,
  0.032501220703125,
  0.019256591796875,
  0.007568359375,
  -0.01776123046875,
  0.028045654296875,
  -0.02374267578125,
  0.0170440673828125,
  0.026947021484375,
  0.019287109375,
  -0.004253387451171875,
  -0.00567626953125,
  -0.0233306884765625,
  -0.004993438720703125,
  0.0301055908203125,
  -0.0305023193359375,
  -0.04241943359375,
  0.0302276611328125,
  -0.046783447265625,
  0.0201873779296875,
  -0.0290069580078125,
  0.022430419921875,
  0.0208587646484375,
  0.004489898681640625,
  0.017669677734375,
  0.053314208984375,
  0.03131103515625,
  -0.023834228515625,
  0.00921630859375,
  0.0133514404296875,
  0.0100555419921875,
  -0.00946044921875,
  0.03271484375,
  0.0247802734375,
  -0.0193939208984375,
  -0.01477813720703125,
  0.00449371337890625,
  0.008575439453125,
  -0.01513671875,
  0.0166473388671875,
  0.027587890625,
  0.003726959228515625,
  0.006023406982421875,
  0.0036773681640625,
  -0.001125335693359375,
  -0.005023956298828125,
  0.043670654296875,
  -0.043182373046875,
  -0.038970947265625,
  -0.043365478515625,
  0.034027099609375,
  -0.038909912109375,
  -0.016876220703125,
  0.015625,
  -0.036102294921875,
  0.0038700103759765625,
  -0.023223876953125,
  0.01593017578125,
  0.060943603515625,
  -0.0126495361328125,
  -0.03167724609375,
  0.01360321044921875,
  0.0198516845703125,
  -0.0374755859375,
  -0.0286407470703125,
  -0.0196685791015625,
  0.0074462890625,
  0.0270233154296875,
  0.002544403076171875,
  0.0231475830078125,
  0.0021209716796875,
  -0.04974365234375,
  0.034912109375,
  -0.0188446044921875,
  0.004894256591796875,
  -0.0026493072509765625,
  0.00858306884765625,
  -0.00955963134765625,
  -0.05224609375,
  0.005527496337890625,
  0.019805908203125,
  0.0216522216796875,
  -0.0281829833984375,
  0.0098876953125,
  -0.022613525390625,
  -0.036651611328125,
  0.016143798828125,
  -0.0266571044921875,
  -0.01071929931640625,
  0.06695556640625,
  -0.01203155517578125,
  0.031097412109375,
  -0.0224609375,
  -0.0248870849609375,
  -0.05596923828125,
  0.0300140380859375,
  -0.0121917724609375,
  0.03521728515625,
  -0.0236968994140625,
  -0.01294708251953125,

In [47]:
# upload to vector db
def upload_to_vector_db(pointstructs, batch_size=100):
    counter = 1
    for i in range(0,len(pointstructs), batch_size):
        batch = pointstructs[i:i+batch_size]    

        qdrant_client.upsert(
            collection_name=COLLECTION_NAME,
            points=batch,
            wait=True
        )
        print(f"Processed {counter * batch_size} / {len(pointstructs)}")
        counter += 1

In [48]:
upload_to_vector_db(pointstructs)

Processed 100 / 1000
Processed 200 / 1000
Processed 300 / 1000
Processed 400 / 1000
Processed 500 / 1000
Processed 600 / 1000
Processed 700 / 1000
Processed 800 / 1000
Processed 900 / 1000
Processed 1000 / 1000

### Searching a prefiltered set of product ids

In [ ]:
from qdrant_client.http.models import FusionQuery
from qdrant_client.http.models import MatchAny
def prefiltered_reviews(query: str, parent_asins: list[str], k: int = 10) -> str:
    query_embedding = get_embeddings_batch(query)[0]

    #hybrid retrieval
    results = qdrant_client.query_points(
        collection_name=COLLECTION_NAME,
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin", 
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            ),
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )

    return results

In [56]:
reviews = prefiltered_reviews("itunes", ["B0BKVR14JN", "B09KQP2H7N", "B0C996WY16"])
reviews.points

[ScoredPoint(id=216, version=10, score=0.5, payload={'preprocessed_content': 'MP3 Player with 32GB TF Card,Built-in HD Speaker,Portable HiFi Music Player with Video/Voice Recorder/FM Radio/Photo Viewer/E-Book Player for Kids [\'Xidehuy Music Playeris fashion and delicate in design.you can take it anywhere with your favorite songs, videos, e-books and important files. It is an economical gift for yourself, your family and your friends. Warm Notice:Large capacity, a 32 GB memory card is included. (Support up to 128 GB Card for Maximum). ●Screen Size: 1.8" High Resolution Real Color LCD Screen ●Built-in Li-ion battery, can be charged via USB cable to the PC or wall socket adapter ●Charging time: about 1 hours. Warm reminder: it is recommended to turn on the player before charging. ●Product weight (package not included): about 0.029kg ●Playing time: about 8-12hours ●MP3 Size: 3.5 x 1.5 x 0.3 in ●Support music playback format: MP3、WMA、OGG、APE、FLAC、WAV、AAC-LC、ACELP ●Video format: This player recognizes AMV and AVI video files(It needs Actions Media Player Tools to convert). ●Picture browsing format:JPEG、BMP、GIF ●Record: Voice can be recorded and saved in WAV or MP3 format.Phase/Contrast repeat available. ●E-book: support TXT format ●FM Radio: 87.5MHz~108MHz, save up to 30 channels ●Support Micro SD/MMC/SDHC card ●Tools: It support: “Calendar, Stopwatch, Alarm clock.” ●Settings: All the function attribute display and setting. REMINDER :How to Copy Music To the MP3 Player: Connect it to the computer and it shows up as an external device. Click on it and drag and drop files into it. This MP3 Player does not work with itunes. And this is NOT APPLE ipod. This is Simple MP3 player What is in the Package:1 x MP3/MP4 Player 1 x 32GB memory Card 1 x HiFi bass Earphone 1 x USB Cable 1 x User Manual Product Description\']', 'parent_asin': 'B0BKVR14JN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=484, version=12, score=0.33333334, payload={'preprocessed_content': 'Raymate Bluetooth Speakers, HiFi Stereo Sound with DSP, 30W IPX7 Waterproof Speaker Wireless Bluetooth-V5.0, 1000mins Playtime, Portable Speaker for Home, Outdoor, Party []', 'parent_asin': 'B0C996WY16'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=624, version=14, score=0.25, payload={'preprocessed_content': 'Kids Wireless Headphones, Adjustable Headband, Stereo Sound, 3.5mm Jack, Kids Bluetooth Headphones, Volume Control, Foldable, Build-in Microphone, Over-Ear Headphones for Kids for School Home, Yellow []', 'parent_asin': 'B09KQP2H7N'}, vector=None, shard_key=None, order_value=None)]

In [63]:
from qdrant_client.http.models import FusionQuery
from qdrant_client.http.models import MatchAny
def retrieve_prefiltered_reviews(query: str, parent_asins: list[str], k: int = 10) -> str:
    query_embedding = get_embeddings_batch(query)[0]

    #hybrid retrieval
    results = qdrant_client.query_points(
        collection_name=COLLECTION_NAME,
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin", 
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            ),
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )


    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_content"])
        similarity_scores.append(result.score)
    
    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores
    }


def format_context(context: dict):
    # formatting the retrieved & reranked context
    formatted_context = ""

    for id, review in zip(context["retrieved_context_ids"], context["retrieved_context"]):
        formatted_context += f"- ID: {id}, User Review: {review}\n"

    return formatted_context

In [64]:
def retrieve_formatted_context(query: str, parent_asins: list[str], k: int = 10) -> str:
    """Get the top k user reviews for a list of prefiltered items, based on the provided parent asin.

    Arg:
        query: The search string that is used to perform search for user reviews
        parent_asins: The list of item IDs to prefilter the reviews
        k: Top k items that will be returned by the tool

    Returns:
        A formatted string that contains the k user reviews for the prefiltered product ids that best fit the searched query
    """
    retrieved_context = retrieve_prefiltered_reviews(query=query, parent_asins=parent_asins, k=k)
    formatted_context = format_context(retrieved_context)
    return formatted_context

In [65]:
result = retrieve_formatted_context("itunes", ["B0BKVR14JN", "B09KQP2H7N", "B0C996WY16"])

In [67]:
print(result)

- ID: B0BKVR14JN, User Review: MP3 Player with 32GB TF Card,Built-in HD Speaker,Portable HiFi Music Player with Video/Voice Recorder/FM Radio/Photo Viewer/E-Book Player for Kids ['Xidehuy Music Playeris fashion and delicate in design.you can take it anywhere with your favorite songs, videos, e-books and important files. It is an economical gift for yourself, your family and your friends. Warm Notice:Large capacity, a 32 GB memory card is included. (Support up to 128 GB Card for Maximum). ●Screen Size: 1.8" High Resolution Real Color LCD Screen ●Built-in Li-ion battery, can be charged via USB cable to the PC or wall socket adapter ●Charging time: about 1 hours. Warm reminder: it is recommended to turn on the player before charging. ●Product weight (package not included): about 0.029kg ●Playing time: about 8-12hours ●MP3 Size: 3.5 x 1.5 x 0.3 in ●Support music playback format: MP3、WMA、OGG、APE、FLAC、WAV、AAC-LC、ACELP ●Video format: This player recognizes AMV and AVI video files(It needs Actions Media Player Tools to convert). ●Picture browsing format:JPEG、BMP、GIF ●Record: Voice can be recorded and saved in WAV or MP3 format.Phase/Contrast repeat available. ●E-book: support TXT format ●FM Radio: 87.5MHz~108MHz, save up to 30 channels ●Support Micro SD/MMC/SDHC card ●Tools: It support: “Calendar, Stopwatch, Alarm clock.” ●Settings: All the function attribute display and setting. REMINDER :How to Copy Music To the MP3 Player: Connect it to the computer and it shows up as an external device. Click on it and drag and drop files into it. This MP3 Player does not work with itunes. And this is NOT APPLE ipod. This is Simple MP3 player What is in the Package:1 x MP3/MP4 Player 1 x 32GB memory Card 1 x HiFi bass Earphone 1 x USB Cable 1 x User Manual Product Description']
- ID: B0C996WY16, User Review: Raymate Bluetooth Speakers, HiFi Stereo Sound with DSP, 30W IPX7 Waterproof Speaker Wireless Bluetooth-V5.0, 1000mins Playtime, Portable Speaker for Home, Outdoor, Party []
- ID: B09KQP2H7N, User Review: Kids Wireless Headphones, Adjustable Headband, Stereo Sound, 3.5mm Jack, Kids Bluetooth Headphones, Volume Control, Foldable, Build-in Microphone, Over-Ear Headphones for Kids for School Home, Yellow []